### ISSUE TITLE
Add some images that can be loaded via the public API

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#101]
We now have one image in the repo: ``demo/data/aero.png``. We can't use that in docstring examples however, because it's not importable. Nicer docstring examples instead of just the return values of some random numbers would be very good to have. 
We could easily add ``scipy.misc.face`` and ``scipy.misc.ascent`` next to ``aero``.

**Comment by grlee77** [comment]
``skimage/data/camera.png`` from scikit-image is another possibility.
