### ISSUE TITLE
sharing PyPi & ReadTheDocs access rights

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#110]
Hi @grlee77 @aaren @kwohlfahrt, I'll be offline for a month and a half from the 21st on. So I'd like to give some or all of you access to PyPi and ReadTheDocs for this project. If you tell me your username for those sites then I'll do that.

**Comment by aaren** [comment]
I'm `aaren` on both pypi and readthedocs.

**Comment by grlee77** [comment]
I'm ``grlee77`` on both.  (just created the ReadTheDocs one)

**Comment by kwohlfahrt** [comment]
`kwohlfahrt` on both, just registered.

**Comment by rgommers** [comment]
Thanks, you all have access on both sites now.

**Comment by rgommers** [comment]
I've also created https://ci.appveyor.com/project/PyWavelets/pywt and removed the config on my personal Appveyor account. If you register on www.appveyor.com I can add you as a collaborator (need the email address you registered with for that, not your username).

**Comment by aaren** [comment]
Have signed up to appveyor, using github. Didn't put an email in but presume it is same as my commit email.

**Comment by rgommers** [comment]
Yep, that works - you're in @aaren

**Comment by kwohlfahrt** [comment]
@rgommers I'm late to the party, but I've also signed up to appveyor (initially using my email, but it is also linked to my github account). Can I be added as a collaborator please?

**Comment by rgommers** [comment]
@kwohlfahrt I've added the PyWavelets Core team with Admin rights to the account, so you should have access now. If that doesn't work, which of your email addresses do I use?

**Comment by kwohlfahrt** [comment]
Works, I had to log out and then log back in with github in case anybody else runs into that problem. Thanks!
