### ISSUE TITLE
Failing tests across all builds due to complex

### ISSUE THREAD

**Issue by aaren** [PyWavelets/pywt#111]
master branch is failing tests.

I noticed this when building #55 but it seems to apply on master as well. Probably something to do with #99 being merged, although that was rebased prior to merge and the tests were all passing.

@grlee77 @kwohlfahrt any ideas?

**Comment by kwohlfahrt** [comment]
`dwtn` and `idwtn` don't seem to respect complex data types. I think this is because the changes in #99 modified `upcoef` and `downcoef`, but as of #104 these are no longer used by `dwtn`/`idwtn`. Perhaps #99 was not rebased onto this prior to merge?

**Comment by aaren** [comment]
I see now. I got trigger happy with merging and should have waited to merge #99 before I merged #104. @grlee77 did rebase #99, but I merged #104 *after* he did that, leading to this problem.

**Comment by grlee77** [comment]
should I submit a quick PR to fix complex for dwtn and idwtn based on current master then?

**Comment by aaren** [comment]
yes please!

**Comment by kwohlfahrt** [comment]
Sorry, should've said I'd picked this up.

**Comment by grlee77** [comment]
@kwohlfahrt.  no worries.  thanks for taking the initiative

**Comment by aaren** [comment]
Thanks both for quick response. I've learned a lesson about merging.
