### ISSUE TITLE
Add db40 to wave list

### ISSUE THREAD

**Issue by drew-wallace** [PyWavelets/pywt#118]
I'm doing some experiments and need this wave. Can this be done?

**Comment by kwohlfahrt** [comment]
The coefficients are not built in (only up to 'db20' iirc), but you can create your own wavelet using `pywt.Wavelet(name, filter_bank=[dec_lo, dec_hi, rec_lo, rec_hi])`, where the dec/rec are the deconstruction and reconstruction coefficients, and lo/hi are the approximation and detail coefficients respectively.

I'm not aware of any plans to extend the builtin filters all the way up to db40, but it might be fun to implement the construction function for daubechies wavelets to allow arbitrary ones. Looks straightforward at first glance, I'll have a look in the coming week or so.

**Comment by drew-wallace** [comment]
I found the coefficients for db2-99 here: https://github.com/fukuroder/daubechies_wavelet_coefficients/tree/master/coefficients. I did a spot check for db20 and they match (in reverse order). I may just add it into the code myself.

**Comment by kwohlfahrt** [comment]
Sorry for the delay, but after a quick look it seems that a built-in solver would be necessary to allow arbitrary wavelets, which is a little beyond the scope of the project. Given that custom filter banks are possible, I don't think adding more is a priority unless there is a lot of demand for wavelets beyond 'db20'.

**Comment by grlee77** [comment]
If you think there is a particular wavelet that would be of widespread general interest feel free to make a case for it and we may include it in a future release.  Otherwise, you can follow the instructions above to use your own custom wavelet coefficients.
