### ISSUE TITLE
cythonizing the C source

### ISSUE THREAD

**Issue by aaren** [PyWavelets/pywt#126]
Is there a reason why the C source code couldn't be cythonized? Would this remove the need for the current templating mechanism?

Aside from the work needed would it be otherwise desirable to do this?

**Comment by rgommers** [comment]
I think @kwohlfahrt still has plans to reuse the C code standalone (i.e. not from Python). So it probably matters to him.

**Comment by rgommers** [comment]
I'm not too bothered by the templating, but Cython fused types would be nicer.

**Comment by kwohlfahrt** [comment]
In addition to what @rgommers said, there are more tools around to help optimize C code - clang's `-Rpass=missed-loop-vectorize` and the like. Cython's C code isn't very readable so the information there is generally not as useful.

Also (I know numpy is against this, so it would be done only on the condition it doesn't affect single-threaded performance or compatibility), OpenMP is maturing in GCC and clang, so it would be nice to add that, especially once GPU offloading gets put together.

**Comment by rgommers** [comment]
I don't know much about OpenMP, but if it can be optionally enabled in the build and it's important to you, then I don't see a problem adding it here. In this package we can be much less strict than in numpy/scipy I think.

**Comment by kwohlfahrt** [comment]
Awesome. A lot of the loops are very straightforward, so we can just use `#pragma omp parallel for` to parallelize them. This should be ignored by any compiler that doesn't know about OpenMP (and it is on GCC/clang if it's not enabled).

**Comment by kwohlfahrt** [comment]
As a different avenue, how about using [Halide](http://www.halide-lang.org)? It seems to be made for exactly this kind of thing, is cross-platform, has python bindings and supports GPU/CPU computing. I haven't ever used it but intend to play with it in the next few months for other work-related tasks, so will report back unless there are any objections.

**Comment by aaren** [comment]
@rgommers could say more but I don't think that will work for integrating into scipy. Would at least require a lot of discussion on the scipy end as it adds a dependency, whereas the existing code can go in without much bother.

**Comment by grlee77** [comment]
@rgommers :  OpenMP can indeed by optionally enabled during build time.  

I am familiar with the [dipy](https://github.com/nipy/dipy) package which basically does a simple compilation test in setup.py that determines whether OpenMP flags get enabled or not.

See here for the specifics:
https://github.com/nipy/dipy/blob/7f73773b3048ae40ccfaa79e2fce343fb2476a82/setup.py#L138-L145

A similar compilation check is used by [yt](https://bitbucket.org/yt_analysis/yt) as well:
https://bitbucket.org/yt_analysis/yt/src/f0e05114dfdc9a068d78373311336b5f6fa14578/yt/utilities/lib/setup.py?at=yt&fileviewer=file-view-default

**Comment by rgommers** [comment]
> As a different avenue, how about using Halide? It seems to be made for exactly this kind of thing, is cross-platform, has python bindings and supports GPU/CPU computing.

Never heard of it, but looks interesting. I'm afraid trying to use it for production code at this point in time is going to be very painful though. For one, platform support is poor ("expect rough edges with the Windows version", unclear if support for anything but Linux/OSX/Windows). It's also a fairly heavy dependency it looks like.

**Comment by rgommers** [comment]
Regarding OpenMP, we do need to document in release notes and other places we can think of that it's used if detected, how it can be disabled in the build, and that it breaks ``multiprocessing`` (see https://github.com/numpy/numpy/issues/5752#issuecomment-90752612).

**Comment by kwohlfahrt** [comment]
Oof, did not realize that clashed. Thanks for the heads up, will try and pin down exactly what situations break.

**Comment by aaren** [comment]
Closing for now. Looks like we'll stick with C.
