### ISSUE TITLE
use refguide_check.py for doctests as in scipy

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#151]
In #150 , during the fixing of doctests, the addition of lines such as
`import numpy as np` are needed for the tests to pass, but tend to clutter the documentation strings a bit.

@rgommers mentioned https://github.com/scipy/scipy/blob/master/tools/refguide_check.py
as a potential solution to the issue

**Comment by rgommers** [comment]
done in gh-220, closing
