### ISSUE TITLE
Gabor Wavelet

### ISSUE THREAD

**Issue by florianletsch** [PyWavelets/pywt#156]
Excuse my potential ignorance, but I am rather new to signal processing in general.
1. Is there any particular reason the Gabor Wavelet is not part of the included Wavelets?
2. I understand I can create a custom Wavelet, provided I pass in the correct coefficients for the filter bank. The Gabor Wavelet is a Gauss multiplied with a cosine function. How do I turn this function in the matching filter bank? I have read the chapter on [Custom Wavelets](http://pywavelets.readthedocs.org/en/latest/ref/wavelets.html#custom-wavelets), but I still don't know how to calculate the actual values.

```
class GaborFilterBank(object):
    @property
    def filter_bank(self):
        return ([...], ... ) # how to determine these coefficients?

gabor = pywt.Wavelet('gabor', filter_bank=GaborFilterBank())
```

**Comment by kwohlfahrt** [comment]
I haven't come across it before, but had a quick read around. Unlike the wavelets included here (except the `dmey` wavelet) it is a continuous wavelet. I'm not sure exact reconstruction is possible with a discrete approximation, there are a couple papers on the subject but it's a bit over my head.

It is probably more suitable as an analysis filter, but I'm not sure it's suitable as a decomposition/reconstruction filter bank in the same way the others are. Somebody with more of a mathematics background would probably be more useful here, but hopefully this helped a bit.

**Comment by aaren** [comment]
@florianletsch It looks like there is an analytic definition of the Gabor wavelet so you could try defining it in my [continuous wavelets package](https://github.com/aaren/wavelets) and see if that works for you. Depends on what sort of problem you're solving and how many dimensions it has? (time-series, image decomposition, something else?)

**Comment by grlee77** [comment]
Also, depending on your application, you may be interested in the discrete Gabor filters available in scikit-image.  Here is an example:
http://scikit-image.org/docs/dev/auto_examples/features_detection/plot_gabor.html

**Comment by florianletsch** [comment]
@grlee77 Thanks. That's the solution I have settled on for now.

**Comment by rgommers** [comment]
looks like the question was answered, and don't see a strong reason to keep this open as a feature request. so closing.
