### ISSUE TITLE
Set up coveralls

### ISSUE THREAD

**Issue by kwohlfahrt** [PyWavelets/pywt#163]
Working on #161 coverage now works very well. We could set up coveralls (or something similar? I don't know any alternatives) to give a more constant overview if people think this would be useful.

**Comment by rgommers** [comment]
An alternative is https://codecov.io/. We switched to that from coveralls.io. They're fairly similar though.

**Comment by kwohlfahrt** [comment]
Sure, I'm not fussed. I have a branch with coveralls at the moment but as far as I can see it'd be a change of 2 lines in `.travis.yml`

**Comment by rgommers** [comment]
Whichever one you prefer I'd say. 

It would probably be good to turn off the feature where the code coverage bot adds a comment with the coverage stats to each PR. That tends to get annoying quickly, especially when adding commits to a PR. As long as there's a link to the results next to the TravisCI/Appveyor ones, that should do the job.

**Comment by kwohlfahrt** [comment]
OK, gave codecov a whirl. Not as pretty, but their website is much more responsive so I'll stick with them. Going to pick off some low hanging fruit and then open a PR (currently based on #161 but that's a big one and it should be possible to rebase if that doesn't get merged).

**Comment by kwohlfahrt** [comment]
I've just spotted this, which looks like something we should definitely use: http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html

However, it seems likely that adding the instrumentation will slow down the generated code. We'll want this disabled for release, but enabled for coverage reports. Any thoughts on how to best enable this? Perhaps some environment variable checked in `setup.py`?

**Comment by rgommers** [comment]
That would be nice indeed. Disable also for normal builds off master I'd think. Maybe just set an envvar and then use ``compiler_directives`` (see http://docs.cython.org/src/reference/compilation.html#in-setup-py) only if that envvar is present? Then we can enable it only on a single TravisCI run where we generate a coverage report, and locally only when needed.

**Comment by kwohlfahrt** [comment]
OK, Cython coverage is working. I've added C instrumentation as well but the analysis is not quite ready. Tests only take about twice as long on my laptop, so I've left them enabled on all CI builds for my branch. We can hash out specifics later.

**Comment by kwohlfahrt** [comment]
OK, I've hit a wall regarding getting C code covered. There are two issues:

- specifying the C sources to each extension module causes them to be rebuilt every time (so the `common.o` file for `_dwt` is rebuilt before compiling `_swt`). This breaks profiling as the `.gcno` files are timestamped.
- Profiling works if the C components are built as a static library. However, this causes horrible breakage everywhere (memory corruption) and I can't figure out why (kwohlfahrt/pywt@551340a20091aa69e43014d8ea41ca4966d6a141).

**Comment by kwohlfahrt** [comment]
Breakage fixed, the macro wasn't correctly defined (use the `'macros'` keyword for clib) so it wasn't using the python allocator. It also needs to be defined for the cython extensions, not sure why

Now it's just a little irritating that the c library is always rebuilt regardless of whether the sources have changed, and that a change to the c files no longer triggers the cython modules to be rebuilt (though the latter could be easily fixed by adding their sources as dependencies manually).
