### ISSUE TITLE
SWT on last samples of sequence

### ISSUE THREAD

**Issue by overjoy** [PyWavelets/pywt#173]
Hello everybody and thanks for this great library.
I'm newbie in wavelets and have a question regarding SWT. I don't know if it's a bug or not, but why do I get some weird spikes at the end of sequence? Here is the plot and corresponding code:
![swt](https://cloud.githubusercontent.com/assets/510509/13669752/8d36f952-e6d6-11e5-9299-32a3002b65f3.png)

```
import pywt
import numpy as np
import matplotlib.pyplot as plt

# generate some random signal 
x = np.arange(64)
s = np.sin(x/(2*np.pi)) + np.cos(x/(5*np.pi)) + 0.2*np.random.randn(len(x))

# full SWT decomposition
(A2,D2),(A1,D1) = pywt.swt(s, 'haar', 2)
plt.plot(A2, 'b')

# SWT of first 32 samples only
(A2,D2),(A1,D1) = pywt.swt(s[:32], 'haar', 2)
plt.plot(A2, 'ro')
plt.show()
```

I'm using approximation and detail sequences as inputs of neural network and I think that spiky behaviour will ruin my plans because it makes last samples very misleading. 
If it is the expected result of SWT, does anybody know how to overcome this issue? Or maybe guide me to some good introduction to SWT.. Everything I found in net was like rocket-science-ego-maniac-mathematical stuff. Can't believe such a thing can not be explained without tons of integrals.

**Comment by kwohlfahrt** [comment]
I think this is due to the signal extension (to generate the last few elements of the decomposition, the wavelet has to be multiplied with values *past* the end of the signal). These are generated from a number of available signal extension modes (see `pywt.Modes`) for the DWT. For SWT, the `periodization` mode is used, so the samples at the very end are influenced by those at the beginning.

**Comment by grlee77** [comment]
Agreed.  There is detailed discussion of these border effects here
http://www.mathworks.com/help/wavelet/ug/dealing-with-border-distortion.html
(The border modes in pywt match those available in Matlab)

**Comment by overjoy** [comment]
Well.. This border effect is present on both sides or only in the end of a sequence? I tried to reverse the sequence before decomposition and then reverse decomposed coefficients back. The result is shifted. Can't figure out why. Here is the plot of signal with level 4 approximations:

![figure_13](https://cloud.githubusercontent.com/assets/510509/13797932/2f533710-eb22-11e5-90f3-d0030a960695.png)

**Comment by kwohlfahrt** [comment]
Looks like the question has been answered. Feel free to re-open if it is not clear.
