### ISSUE TITLE
length of returned arrays

### ISSUE THREAD

**Issue by nareto** [PyWavelets/pywt#175]
why does pywt.dwt(np.arange(8),'db2') return two arrays of size 5 each? As far as I understand the DWT should always do a downsampling of size 2, no matter the length of the filter... Am I missing something?

EDIT: where of course I did `import numpy as np` before

**Comment by kwohlfahrt** [comment]
The default is to pad the signal (there are multiple padding methods available). For the minimum signal length (i.e. 2x downsampling), the `"periodization"` mode should be used. Detailed documentation is [here](http://pywavelets.readthedocs.io/en/latest/ref/signal-extension-modes.html).

**Comment by kwohlfahrt** [comment]
Closing, think the question is answered. Re-open if not.
