### ISSUE TITLE
Fail to install pywt due to the use of index_t which conflict with the defination in /usr/include/sys/types.h on smartos sysmte(open solaris like system)

### ISSUE THREAD

**Issue by FrankYu** [PyWavelets/pywt#177]
#git describe
v0.4.0-83-g416c697

#python setup.py install 
Cythonizing sources
pywt/_extensions/_swt.pyx has not changed
pywt/_extensions/_pywt.pyx has not changed
pywt/_extensions/_dwt.pyx has not changed
/opt/local/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
building extension "pywt._extensions._pywt" sources
building extension "pywt._extensions._dwt" sources
building extension "pywt._extensions._swt" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
copying pywt/version.py -> build/lib.solaris-2.11-i86pc.64bit-2.7/pywt
copying build/src.solaris-2.11-i86pc.64bit-2.7/pywt/__config__.py -> build/lib.solaris-2.11-i86pc.64bit-2.7/pywt
copying build/src.solaris-2.11-i86pc.64bit-2.7/pywt/_extensions/__config__.py -> build/lib.solaris-2.11-i86pc.64bit-2.7/pywt/_extensions
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building 'pywt._extensions._pywt' extension
compiling C sources
C compiler: gcc -fno-strict-aliasing -pipe -O2 -pipe -O2 -DHAVE_DB_185_H -pthread -I/usr/include -I/opt/local/include -I/opt/local/include/db4 -I/opt/local/include/ncurses -DNDEBUG -pipe -O2 -pipe -O2 -DHAVE_DB_185_H -pthread -I/usr/include -I/opt/local/include -I/opt/local/include/db4 -I/opt/local/include/ncurses -fPIC

compile options: '-DPY_EXTENSION -Ipywt/_extensions/c -I/opt/local/lib/python2.7/site-packages/numpy-1.12.0.dev0+4ccf3d7-py2.7-solaris-2.11-i86pc.64bit.egg/numpy/core/include -I/opt/local/lib/python2.7/site-packages/numpy-1.12.0.dev0+4ccf3d7-py2.7-solaris-2.11-i86pc.64bit.egg/numpy/core/include -I/opt/local/include/python2.7 -c'
gcc: pywt/_extensions/c/common.c
In file included from pywt/_extensions/c/common.c:4:0:
pywt/_extensions/c/common.h:26:24: error: conflicting types for 'index_t'
In file included from /usr/include/memory.h:31:0,
                 from pywt/_extensions/c/common.h:9,
                 from pywt/_extensions/c/common.c:4:
/usr/include/sys/types.h:127:16: note: previous declaration of 'index_t' was here
In file included from pywt/_extensions/c/common.c:4:0:
pywt/_extensions/c/common.h:26:24: error: conflicting types for 'index_t'
In file included from /usr/include/memory.h:31:0,
                 from pywt/_extensions/c/common.h:9,
                 from pywt/_extensions/c/common.c:4:
/usr/include/sys/types.h:127:16: note: previous declaration of 'index_t' was here
error: Command "gcc -fno-strict-aliasing -pipe -O2 -pipe -O2 -DHAVE_DB_185_H -pthread -I/usr/include -I/opt/local/include -I/opt/local/include/db4 -I/opt/local/include/ncurses -DNDEBUG -pipe -O2 -pipe -O2 -DHAVE_DB_185_H -pthread -I/usr/include -I/opt/local/include -I/opt/local/include/db4 -I/opt/local/include/ncurses -fPIC -DPY_EXTENSION -Ipywt/_extensions/c -I/opt/local/lib/python2.7/site-packages/numpy-1.12.0.dev0+4ccf3d7-py2.7-solaris-2.11-i86pc.64bit.egg/numpy/core/include -I/opt/local/lib/python2.7/site-packages/numpy-1.12.0.dev0+4ccf3d7-py2.7-solaris-2.11-i86pc.64bit.egg/numpy/core/include -I/opt/local/include/python2.7 -c pywt/_extensions/c/common.c -o build/temp.solaris-2.11-i86pc.64bit-2.7/pywt/_extensions/c/common.o" failed with exit status 1

**Comment by grlee77** [comment]
closed by #178
