### ISSUE TITLE
'reflect' signal extension mode

### ISSUE THREAD

**Issue by JohnLunzer** [PyWavelets/pywt#187]
I've noticed that PyWavelets lacks an important signal extension mode, which is `'reflect'`:

It would look like this:
`... x3 x2 | x1 x2 x3 ... xn-2 xn-1 xn | xn-1 xn-2 ...`

This extension mode is what is prescribed in the DWT section of the JPEG2000 standard. I assume it is used elsewhere as well.

Please see `numpy.pad`'s `'reflect'` mode as an additional example:
http://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

I believe a mode would need to be added to three of the four steps (those dealing with the edges) in `pywt/_extensions/c/convolution.template.c`.

I would do this myself but my C is a little rusty and I am time limited at the moment. For someone adept with C I think the existing code for the 'symmetric' mode could serve as a starting point. 

Please let me know if anyone has any questions.

**Comment by grlee77** [comment]
This is a reasonable request and also appears to be a mode that is supported in recent versions of Matlab (under the name `symw`).

See #193 for a proposed implementation.

**Comment by grlee77** [comment]
Hi @JohnLunzer , if have merged the requested extension mode into master.
