### ISSUE TITLE
bump minimum numpy version?

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#189]
I noticed that the `README.md` states that we support numpy >=1.6.2, but 1.7.2 seems to be the oldest version we test on Travis.  

Is there any objection to bumping the minimum numpy version?  I would be inclined to bump to **1.9** which is almost exactly 2 years old at this point.  What do others think?

Two recent examples where we wanted to use newer functionality (there are probably more I am forgetting):
in #168 we have a substitute function for `np.full` which was only introduced in 1.8
For #172, it would be nice to have the `dtype` argument to `np.linspace` which was introduced in 1.9

**Comment by rgommers** [comment]
I think it's a good idea to bump as needed when we want to use new functionality in numpy, as long as we keep at least 2 years worth of releases or 2 versions. So up to 1.9.3 is fine with me.

**Comment by grlee77** [comment]
version bumped by #190
