### ISSUE TITLE
building in-place for development.

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#196]
With setup.py as currently configured, one cannot build for development using simply
```pip install -e .``` from within  the source tree, but must first call `python setup.py build_clib` to make sure the c library is built first.  I think setup.py was structured as is to get coverage of the C code to work properly.  

I couldn't find an option for pip that would cause it to first call `build_clib`, but maybe I have missed something?  Is there another easier way?  It is not a big deal, but perhaps worth adding a note to the docs on how to best build in-place for development.

**Comment by rgommers** [comment]
It should never be needed to call ``build_clib`` for anything I think, that command is more or less an implementation detail (``build_ext`` is more common though for in-place builds). I don't see anything unusual in ``setup.py`` that should break something. I'll give it a try now.

**Comment by rgommers** [comment]
Both ``pip install -e .`` and ``python setup.py develop`` work as expected for me. What is the problem exactly for you?

**Comment by rgommers** [comment]
Sorry, new laptop - was pulling from my own repo which is behind. Current master is indeed broken. Will see if I can find a cure.

**Comment by rgommers** [comment]
OK ugly fix in gh-197.
