### ISSUE TITLE
Remove legacy copies of docs

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#215]
`pythonhosted` is deprecated, so http://pythonhosted.org/PyWavelets/ needs to go.

There's also still an even older copy at http://www.pybytes.com/pywavelets/ which people are finding (example: https://github.com/nigma/pywt/issues/17#issuecomment-253165926)

**Comment by rgommers** [comment]
would be best to go readthedocs-only in v0.5.0, because links in a release readme last a while. I'll try to do this over the weekend.

**Comment by nigma** [comment]
Right. I'll take care of the one at pybytes.com over the weekend and see how to add redirects to Sphinx templates.

**Comment by rgommers** [comment]
great, thansk @nigma

**Comment by nigma** [comment]
I added a notice on the site and an automatic redirect from http://www.pybytes.com/pywavelets/ to https://pywavelets.readthedocs.io/en/latest/. We can do something similar for *pythonhosted* if you want.

**Comment by rgommers** [comment]
That looks good @nigma. If you could put the same notice and redirect on pythonhosted, that would be great.

**Comment by grlee77** [comment]
@nigma, @rgommers

The pybytes redirect is working, but there is not one on pythonhosted yet.  Would the following `index.html` be sufficient to upload as the documentation on PyPI for v0.5.0?  I think @nigma used a javascript-based solution at  pybytes which is perhaps better, but I have minimal web programming experience. 

```html
<html>
<head>
 <meta HTTP-EQUIV="REFRESH" content="5; url=https://pywavelets.readthedocs.io/en/latest">
 </head>
<body>
<p>You have reached an outdated location for the PyWavelets documentation.  You
will be automatically redirected to the new location:
<a href="https://pywavelets.readthedocs.io/en/latest/">
https://pywavelets.readthedocs.io/en/latest/</a> in 5 seconds. </p>
</body>
</html>
```

**Comment by rgommers** [comment]
My web programming skills are at about the same level, so if that does the job then LGTM.

**Comment by grlee77** [comment]
Okay, I have done the upload at PyPI and http://pythonhosted.org/PyWavelets seems to be redirecting (at least for Firefox and Chromium).

**Comment by rgommers** [comment]
Thanks!
