### ISSUE TITLE
Updating project info on OpenHub

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#216]
I noticed that the project info on `OpenHub` (https://www.openhub.net/p/PyWavelets) (formerly Ohloh) was pointing to the old `bitbucket` repo.  I just updated the repository link to point here and updated the description slightly.  The site auto-analyzes lines of code, level of activity, etc.  Just by changing the repo URL, the project status has been updated from **inactive** to **moderately active**.

I requested manager access from @nigma, but that is not too critical because the info all seems to currently be publicly editable.  Should we disable public edits of the info there?  (to do so requires manager access)

**Comment by rgommers** [comment]
disabling public access would make sense I guess, but not critical. Having multiple managers would be good

> I requested manager access from @nigma

I just did the same

**Comment by nigma** [comment]
I added Ralf to managers, but I didn't receive any other requests. @grlee77 can you try again?

**Comment by grlee77** [comment]
Yes, I think I never hit send.  I just did it now.

**Comment by rgommers** [comment]
you're in!
