### ISSUE TITLE
NameError: 'cwt' is not defined

### ISSUE THREAD

**Issue by ArasAwas** [PyWavelets/pywt#232]
Hello,
I installed today pywt using easy_install, but when I'm trying to run example with cwt from your docs (http://pywavelets.readthedocs.io/en/latest/ref/cwt.html) I get error message "NameError: name 'cwt' is not defined"
I run demo from your repository named plot_wavelets.py but I didnt get any errors for functions .Wavelet and .wavelist
I tried using Python 2.7 and 3.5.
Can anyone help me fix this?

**Comment by rgommers** [comment]
Hi @ArasAwas, did you install the master branch from GitHub, or v0.4.0 (latest release)? ``cwt`` is not in v0.4.0

**Comment by ArasAwas** [comment]
Thank you for your response,
you're right, I have version 0.4.0, I tried to install one from master and I had problems installing it but didn't noticed its different version. I see now that my it's the same problem like #231 so I could find solution for my problem, so now I have installed succesfully the newest version from Github branch. 
Thank you for pointing it out, because I didnt noticed it and sorry for such trivial issue

**Comment by rgommers** [comment]
No problem at all!
