### ISSUE TITLE
wavedec2 and waverec2 applied consecutively don't return original image

### ISSUE THREAD

**Issue by rohannaidu** [PyWavelets/pywt#233]
See my notebook [here](https://github.com/rohannaidu/applied_harmonic_analysis/blob/master/pywavelets%202d%20transforms.ipynb) for the issue.

Essentially, using transform = wavedec2(image) and recovery = waverec2(transform) should give me recovery==image. But this is not the case...

What am I doing wrong?

**Comment by grlee77** [comment]
I am not sure I see the problem in your example.  The root mean square error you observed is on the order of 1e-8?  When I ran on my machine from current master this was on the order of 9e-11 which is better, but either way that seems pretty good for images scaled in the range [0, 255].  The implementation is based on convolutions using floating point arrays, so there will be some degree of numerical error and the difference image will not look like zeros.

**Comment by grlee77** [comment]
does not seem to be a bug, so closing this one.  Please use the mailing list at http://groups.google.com/group/pywavelets for general questions on usage.
