### ISSUE TITLE
problem uploading to PyPI

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#241]
@matthew-brett kindly built the OS X and manylinux wheels for the v0.5.0 release.  I gave him "Maintainer" access on PyPI, but he encountered the following issue (excerpt from a conversation on Scipy-User)

```
twine upload -s PyWavelets-0.5.0-cp2*

Uploading distributions to https://upload.pypi.org/legacy/

Uploading PyWavelets-0.5.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

[================================] 1759042/1759042 - 00:00:02

HTTPError: 400 Client Error: author_email: Invalid email address. for
url: https://upload.pypi.org/legacy/

I guess this is because of:

https://github.com/PyWavelets/pywt/blob/master/setup.py#L213

maintainer_email="http://groups.google.com/group/pywavelets",
```

**Comment by rgommers** [comment]
That's an odd message. A single maintainer email address in ``setup.py`` and multiple PyPI admins will be very common, hard to imagine that's disallowed.

**Comment by matthew-brett** [comment]
I guess it's checking whether the text in the `maintainer_email` field is a valid email address, with an `@` sign and so on.
