### ISSUE TITLE
Adding community guidelines or CoC

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#267]
Hi all, I propose to add either a community guidelines statement or a code of conduct (CoC). Options:

- Community guidelines could be something like http://scikit-image.org/community_guidelines.html
- CoC could be something like http://www.numfocus.org/code-of-conduct.html

CoC is more common, but personally I have a preference for community guidelines. Here is a scikit-learn thread with rationale for why community guidelines instead of CoC that I agree with: https://groups.google.com/forum/#!msg/scikit-image/WFLLC0TyS8M/OtmA0xd1AwAJ

It's more important I think to add some welcoming statement then argue over what form exactly, so if @PyWavelets/core prefers CoC that's fine with me too.

**Comment by rgommers** [comment]
This is something modern mature open source projects should have, so I added the 1.0 milestone.

**Comment by grlee77** [comment]
I agree this would be good to add.  Community guidelines are fine by me.

**Comment by rgommers** [comment]
Reading the above, the scikit-image guidelines are preferable over the poor CoC that the Contributor Covenant is. However, after having gone through a long process to get the SciPy CoC (https://docs.scipy.org/doc/scipy/reference/dev/conduct/code_of_conduct.html) in place, I do think that a CoC is needed, and has significantly more impact than a non-standard community guidelines. I don't have time to do more right now, but would like to come back to this before the 1.0 release. Hence reopening this issue.

**Comment by grlee77** [comment]
Scikit-image is now in the process of adopting the SciPy code of conduct (#4202). I vote that we just do the same here as well.

**Comment by rgommers** [comment]
Sounds good to me!
