### ISSUE TITLE
Python 3.6 wheels

### ISSUE THREAD

**Issue by matthew-brett** [PyWavelets/pywt#271]
OK for me to upload wheels for Python 3.6?  I just built them: https://travis-ci.org/MacPython/pywavelets-wheels/builds/191711596

**Comment by grlee77** [comment]
Sure.  That would be great.  Thanks!

**Comment by rgommers** [comment]
Go for it. Thanks Matthew!

**Comment by rgommers** [comment]
done, closing. thanks again Matthew
