### ISSUE TITLE
0.5.2 release?

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#274]
in 0.5.1, `pywt.data.nino` is incompatible with numpy 1.12 due to a non-integer index.  This causes one doctest to fail and prevents running the CWT demo.  Maybe worth making a 0.5.2 release incorporating just the fix in #273?

**potential fixes to include in 0.5.2**

- closed PRs:  #273, #276, #289, #292, #291, #294, #295

**Comment by rgommers** [comment]
Sounds good to me. The doctest isn't important, but the CWT one is annoying especially given that CWT is new in 0.5.x

**Comment by grlee77** [comment]
updated the list again.  we are almost there for 0.5.2

I think #291 is ready to merge.

Came across #294 yesterday when working locally on code related to the fully separable transforms for #204.  It should be pretty simple to review.

**Comment by rgommers** [comment]
I'll be able to review in a couple of hours.

**Comment by rgommers** [comment]
The doc build on readthedocs just failed, I'll have a look now. Other than that things are good to go for 0.5.2 I'd say.
