### ISSUE TITLE
Conservation of Energy

### ISSUE THREAD

**Issue by lucianomagrini** [PyWavelets/pywt#278]
Dears,  
the Parseval's Theorem show that the energy it's conserved in time and frequency domain, right?

I'm using the continuous wavelet transform in a data set but the energy not conserved! 

This's a fragment of my code:

*********************

escalas = np.linspace(1, 1500, num=3000)
coefs, freq = pywt.cwt(xfast, escalas, 'mexh')
    
power = (abs(coefs)**2)

sum1 = np.sum(np.sum(xfast**2))
sum2 = np.sum(np.sum(power)

********************

The output  show that sum1 is different sum2! (Incorrecty because the Parserval's Theorem show that sum1 = sum2).
There is a constant normalization of coefficients wavelet array non-explicited?

Thansks for help, 
Luciano

PS: Sorry for my english. It isn't very good.
Clique aqui para Responder

**Comment by grlee77** [comment]
The discrete wavelet transforms in PyWavelets are energy preserving, but the continuous wavelet transform is not normalized as you are expecting.  The scaling is the same as in Matlab's `cwt` (there are unit tests that validate the output of these routines vs. pre-stored output from Matlab).  I think the discussion on scaling in Matlab's documentation near the bottom of the following page should apply:
https://www.mathworks.com/help/wavelet/ref/cwt.html

**Comment by lucianomagrini** [comment]
Hi! Thank's for your answer.
I read in the shared link with the scaling "s" is normalized for the factor "1/sqrt(s)" (L2 norm). 
I will introduce this fact em my code. 
If energy conservation happens, I'll post it here for other users!

**Comment by grlee77** [comment]
@lucianomagrini 
Were you able to get the normalization to work as you expected?  I am going to close this for now as the implementation here seems consistent with the Matlab routine we are testing against.
