### ISSUE TITLE
pywt.swt_max_level

### ISSUE THREAD

**Issue by EPinzuti** [PyWavelets/pywt#279]
Hi,

I am getting different results using pywt.swt_max_level function. If I pass to this function the value 2048  the result is 11 since log2(2048)=11 as expected but if I pass the value 1000 the result is 3 that is equivalent to the log10(1000), why?
thanks

**Comment by grlee77** [comment]
That is because 1000 is divisible by 8 (2**3), but not by 16 (2**4).  If you pad the size up to 1024 you will be able to do 10 levels.  numpy.pad is one function that could be used to do the padding.

**Comment by EPinzuti** [comment]
Thanks.
I am a bit confused.
Are swt transform and modwt (matlab) transform different?  Seems that for a complete decomposition of j levels swt requires N (sample size) to be a multiple of 2^j  but I thought it was well-defined for every N.

**Comment by grlee77** [comment]
Yes they are different.  The `swt` in PyWavelets is like `swt` in Matlab, where the size must also be an integer multiple of 2^n for an n-level transform. (Although I should mention that `swt` is not currently guaranteed to give exactly the same output as Matlab.  Only the `dwt/idwt` and `cwt` routines are explicitly tested as matching Matlab's output for the corresponding routines).  The `swt` and `iswt` routines are mainly tested in terms of satisfying the perfect reconstruction property for a round-trip transform.

I think we would be interested in having MODWT as well, but no one has implemented it yet.  See further related discussion in #51
