### ISSUE TITLE
PyWavelets Installation Issues

### ISSUE THREAD

**Issue by sarwatfatimam** [PyWavelets/pywt#281]
Hello, 

I am using 64-bit Anaconda version 4.3.0 with Python 3.6 and PyCharm EDU 3.5 on Windows 8.1. I have tried installing PyWavelets both from Anaconda command prompt and PyCharm packages ( using anaconda python 3.6 and python 3.5 interpreters). I have used following commands on anaconda command prompt. 

1) conda install -c auto PyWavelets/ conda install pywavelets
2) pip install PyWavelets

For 1) PackageNotFoundError: Package missing in current win-64 channels - pywavelets 
For 2) it says failed building wheel for PyWavelets

I have tried adding the pkg manually by downloading it from [here](https://pypi.python.org/pypi/PyWavelets#downloads) `but it still does not work . Kindly let me know what might be the problem? Thankyou.

**Comment by rgommers** [comment]
Hmm, not quite sure about (1). https://github.com/conda-forge/pywavelets-feedstock/pull/10 rebuilt for Python 3.6 two weeks ago. Do you have ``conda-forge`` in your channels?

(2) is clear, if there's no binary then a source build is attempted, and you don't have the right compilers installed for that. 3.6 wheels for Windows are missing on PyPI, that needs fixing.

**Comment by sarwatfatimam** [comment]
Adding conda-forge in channels solved the issue. Thankyou. 
Also, what type of compilers should I have for source build?

**Comment by grlee77** [comment]
On windows with Microsoft Visual Studio you need to match the compiler used to build Python.  For Python 3.6 on Windows this is Microsoft Visual Studio 2015.

It may also be possible to build with mingw/mingw-w64, but I have not tried this and we do not test against that compiler.

**Comment by rgommers** [comment]
The free version of MSVC'15 works fine, so that's an easier option than mingw-w64. For packages without Fortran code, MSVC should probably be preferred.

**Comment by grlee77** [comment]
closing this as 32 and 64-bit windows wheels for Python 3.6 are now on PyPI as well (for release 0.5.1)
