### ISSUE TITLE
Where did iswtn go?

### ISSUE THREAD

**Issue by mackaiver** [PyWavelets/pywt#305]
Hello,
I'm on release 0.5.2 just installed via pypi.

According to the documentation here:
http://pywavelets.readthedocs.io/en/latest/ref/iswt-inverse-stationary-wavelet-transform.html#multilevel-n-dimensional-iswtn

there is a function called `iswtn` to perform the inverse operation of `swtn`. However the method does not seem to exist:
```
AttributeError: module 'pywt' has no attribute 'iswtn'
```
At first glance the method does not appear to be in the source code. It was there in some older commits though.
Is there a workaround I can use to achieve the same thing?

**Comment by grlee77** [comment]
On Mar 21, 2017 9:10 AM, "Kai Brügge" <notifications@github.com> wrote:

>
> I'm on release 0.5.2 just installed via pypi.
>
> According to the documentation here:
> http://pywavelets.readthedocs.io/en/latest/ref/iswt-inverse-
> stationary-wavelet-transform.html#multilevel-n-dimensional-iswtn
>
> there is a function called iswtn to perform the inverse operation of swtn.
> However the method does not seem to exist:
>
>
It is not in 0.5.2.  The documentation is built from the current master
branch which is ahead of the 0.5.2 release.

One option is to build from source by checking out the code from:
https://github.com/PyWavelets/pywt/

If you don't want to hassle with building from source, you can just copy
the iswtn function from here:
https://github.com/PyWavelets/pywt/blob/dd7b79332f6afac345be8dae3e6dffe2edb5facc/pywt/_swt.py#L424
and paste it into the corresponding file from your 0.5.2 installation

The inverse transform is currently slower than the forward one,
particularly if the number of levels is large.  If performance is not
adequate for your application, please let me know as I do have an
alternative implementation that is a bit faster, but not quite in shape for
making a PR to PyWavelets yet.

**Comment by mackaiver** [comment]
> The inverse transform is currently slower than the forward one,
particularly if the number of levels is large.  If performance is not
adequate for your application, please let me know as I do have an
alternative implementation that is a bit faster, but not quite in shape for
making a PR to PyWavelets yet.

The performance should suffice. We're not quite ready for applying this in production yet. I'll let you know if its too slow.
