### ISSUE TITLE
Using Code from PyCWT

### ISSUE THREAD

**Issue by nabobalis** [PyWavelets/pywt#315]
There's been quite a few attempts at a CWT code in Python and I guess most have made use of the Torrance and Compo code and the [Matlab](http://noc.ac.uk/marine-data-products/cross-wavelet-wavelet-coherence-toolbox-matlab) Wavelet ToolBox. kPywavelets was the most complete version which is now renamed as [PyCWT](https://github.com/regeirk/pycwt). 

I recall discussing this at EuroSciPy 2014, that it wouldn't be possible to use any of the resulting python code due to the licensing issues but I was able to get permission from the authors to licence, as BSD, the Python code that used their codebases as inspiration within PyCWT. [I think the permissions](https://github.com/nabobalis/pycwt/tree/master/license) I got via email was enough but I am not very knowledgeable about licences. 

I wasn't sure if there are parts of the code that could be submitted here, at least for the extra functionality to be added to the CWT and the inclusion of cross-wavelets. Obviously any code submitted would need to be rewritten to align with the style and quality of the code used here. I was thinking of the significance calculation, power bias reification and cross-wavelet functions among others. Are there any plans to expand the CWT part of this module?

**Comment by grlee77** [comment]
I think increased CWT functionality would be welcome.  I guess I am a little unclear on exactly what you are proposing here, though.  It seems the functionality you want is already provided by PyCWT (although it has not yet had an official release).  Are you proposing merging PyCWT functions into PyWavelets rather than maintaining a separate PyCWT pacakage?  If they are intended to remain separate, what is the justification for duplicating identical functionality in both places?

Also, is the integration of the desired routines into PyWavelets something you are volunteering to help work on?  If so, then it is much more likely to happen.  I do not personally use the CWT routines and cannot commit much time to that part of the toolbox at the moment, but am willing to help review pull requests by others.

Finally, I see that some SciPy functions are used in PyCWT.  PyWavelets does not currently have SciPy as a dependency, so that will take some discussion on whether it could become either an optional or required dependency.  

attn:
@holgern as contributor of the matlab-like CWT functionality to PyWavelets.  
@aaren had also created some CWT functions at https://github.com/aaren/wavelets

**Comment by grlee77** [comment]
I forgot to mention:  Thank you for working on receiving permission from the original authors to re-license as BSD for PyCWT!  I think that is useful regardless of whether or not this functions end up within PyWavelets.

Personally I think it would be nice to include the functionality here, but lets see what others think.

**Comment by nabobalis** [comment]
What I am proposing is merging in some of the functions in PyCWT here. From my point of view, having two wavelet packages that offer CWT is not viable long term and this is the larger and more popular project. 

So if the idea was to keep extending the CWT within this module,  I want to PR functions or changes for the CWT so we can replicate the functions needed to create T&C style wavelet plots. I just wasn't sure if it was wanted here or if CWT was going to be supported in this module since it did start off as a discrete wavelet package. I can't say I'm that competent at Python or wavelets, so I imagine the PR would take some work to bring it to the standards here.

I didn't develop PyCWT, that was @regeirk who I assume will continue to develop it, all I did was send some emails about the licence. He has been very open to PRs and issues and the project does have a few issues to clear before a 1.0 release. However, If the aim of PyCWT (which has been how I've looked at it) is to be a Python replacement of T&C/Matlab code then I think it is ready bar tests and documentation.

If the idea isn't wanted, we could make PyCWT dependant on pywavelets for mothers and the CWT and we can keep the extra functionally that was based on T&C/Matlab in PyCWT.

**Comment by rgommers** [comment]
https://github.com/regeirk/pycwt#disclaimer now says BSD licensed, however the 3 links to code used show that that code is unlicensed (2x) or says "free for nonprofit use". So I have to ask: @regeirk did you really obtain explicit permission from all those people to use their code under a BSD license and list them as authors?

**Comment by nabobalis** [comment]
@rgommers It was me to obtained the permission. [Here are the emails.](https://github.com/nabobalis/pycwt/tree/master/license). Hopefully that is enough. 

I am not sure if the text in the code was updated to conform with the licence.

**Comment by rgommers** [comment]
@nabobalis thanks, that is perfect!

**Comment by nabobalis** [comment]
Do we need to remove any mention of text in the code? Or other changes? 
I do not want to violate the licence!

**Comment by grlee77** [comment]
> Do we need to remove any mention of text in the code? Or other changes?

Are you asking this for the readme over at PyCWT?  I think the LICENSE.md file you have there is fine.  In the README.md there is currently a statement saying:
"This software is released under a BSD-style open source license."
I would probably just add something like: "(with permission of the original authors of the Matlab packages upon which it is based)" to make it clear that you have explicitly obtained this permission.

For purposes of inclusion in PyWavelets, I believe BSD code is compatible with our MIT license.  I think we would only have to include a copy of the BSD license from PyCWT somewhere.

**Comment by nabobalis** [comment]
I will change that. I am glad that the licences work out!

I think in hindsight, it might be best to revisit this when pycwt gets a full release. With tests and full documentation I believe we will have a better idea of what can and should be ported to pywt. I feel that the pycwt code base is a bit too immature right now. 

Thank you for your assistance.
