### ISSUE TITLE
`pywt.swt_max_level` silently returns unusually low number of levels for non-dyadic series

### ISSUE THREAD

**Issue by shermstats** [PyWavelets/pywt#324]
If I try to pass a numpy array with a dimension that is non-dyadic (isn't an even power of 2), `pywt.swt` returns a wavelet coefficient array with unusually small dimensionality. For example, if I give it an array of size 88373, `pywt.swt_max_level`(88373) gives 0, if I pass that function 88372, it gives 2, and if I pass it 131072 (the next highest power of 2 above 88373), it returns 17, which is log2(131072). If I pass in (131072 * m) for some integer m, it returns some number greater than or equal to 17.  This leads to obvious problems if I try to perform multilevel stationary wavelet noise removal because with fewer levels, there aren't any small coefficients to set to 0.

`PyWavelets` should be able to handle this issue by including a `mode` option like in `pywt.dwt` for padding, or at least offer some kind of a warning for non-dyadic series.

**Comment by grlee77** [comment]
Yes, this is a limitation of the current SWT implementation.  You will need to have a size which is an integer multiple of `2**n` for an `n`-level decomposition.  This can currently best be done by pre-padding with `numpy.pad` up to the desired size prior to calling the `swt` or `iswt`.

I believe this is also a limitation of the `swt` and `iswt` in Matlab, although there they have an `modwt` for 1D signals that works with more arbitrary lengths.

I will keep this issue open as a reminder to add this info to the docstring (maybe in a Notes section) to make it more apparent.

**Comment by grlee77** [comment]
documentation on this was added in #350
