### ISSUE TITLE
How use WT with Morlet wavelet?

### ISSUE THREAD

**Issue by laszukdawid** [PyWavelets/pywt#330]
It's baffling to me how to perform Wavelet transformation using Morlet. When I perform something like
```
wavelet = pywt.DiscreteContinuousWavelet('morl')
data = pywt.wavedec(S, wavelet)
```
then I get 
> Traceback (most recent call last):
>     data = pywt.wavedec(S, wavelet)
>   File "/usr/local/lib/python2.7/dist-packages/pywt/_multilevel.py", line 87, in wavedec
>     wavelet = Wavelet(wavelet)
>   File "pywt/_extensions/_pywt.pyx", line 335, in pywt._extensions._pywt.Wavelet.__cinit__ (pywt/_extensions/_pywt.c:6082)
> AttributeError: 'pywt._extensions._pywt.ContinuousWavelet' object has no attribute 'lower'
> 

I tried with `ContinuousWavelet` and `pywt.dwt`. Continuous transform (cwt) give suspicious results and difficult to plot.
Is this correct?

**Comment by grlee77** [comment]
`wavedec` will only work with discrete wavelets while `Morlet` is a continuous wavelet. `DiscreteContinuousWavelet` is just a utility function that takes any of the wavelet names and returns either a discrete `Wavelet` object or a `ContinuousWavelet` object depending on which type of wavelet the name corresponds to.    We currently only have a single transform function (`cwt`) that works with the continuous wavelets.  The rest all require a discrete wavelet.  

You can get a list of all discrete wavelets via:
```Python
import pywt
print(pywt.wavelist(kind='discrete'))
```
or for all continuous wavelets
```Python
print(pywt.wavelist(kind='continuous'))
```

That said, we could certainly modify `wavedec` and other transform functions to return a more user-friendly error message than the one you encountered here, suggesting use of the proper wavelet type.

**Comment by grlee77** [comment]
I am closing this as `wavedec` is not expected to work with continuous wavelets.  I have opened a related issue in #333 regarding improving the error messages in cases like these.
