### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

### ISSUE THREAD

**Issue by cxxun** [PyWavelets/pywt#334]
like this

D:\Anaconda2\python.exe F:/code/radiomics-master/radiomics/features.py
Traceback (most recent call last):
  File "F:/code/radiomics-master/radiomics/features.py", line 4, in <module>
    import pywt
  File "D:\Anaconda2\lib\site-packages\pywt\__init__.py", line 16, in <module>
    from ._extensions._pywt import *
  File "__init__.pxd", line 155, in init pywt._extensions._pywt
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

Process finished with exit code 1

**Comment by grlee77** [comment]
Have not looked into this yet, but can you specify which OS and what version of PyWavelets you are using.  Is it the conda-forge package  (i.e. `conda install -c conda-forge pywavelets`)?

**Comment by grlee77** [comment]
This sounds like the issue discussed at the link below and is most likely caused by your numpy being older than the version used to compile pywavelets.  Hopefully upgrading numpy will resolve the problem.

https://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling/18369312

**Comment by qimikimy** [comment]
@grlee77 thanks, but my version of numpy has been updated to newest.

**Comment by grlee77** [comment]
Can you please post the result of running `conda info` in a terminal (as well as the output of `conda list`)?  I think we will need more system/platform information to be able to diagnose the problem. 
 
Even better would be if you can provide a simple `conda create` command that would create a clean conda environment where the problem can be reliably reproduced.

**Comment by grlee77** [comment]
If you make a new, minimal clean environment via `conda create -c conda-forge -n pywt_test  pywavelets` do you still see this problem when that environment is active?

**Comment by grlee77** [comment]
closing this for lack of feedback. If you are still experiencing the issue, please post more info on how to reproduce the problem.

**Comment by rgommers** [comment]
This is a harmless warning, and was fixed by numpy 1.15.1
