### ISSUE TITLE
What's the usage of image_blender.py?

### ISSUE THREAD

**Issue by maykef** [PyWavelets/pywt#342]
Hi, 

What's the correct usage of image_blender.py? 
Usage: image_blender.py -b BASE -t TEXTURE -o OUTPUT [-w WAVELET] [-l LEVEL] [-m MODE]
b and t are just the name of the images; but what about -w, -l and -m? Are these numbers? e.g. -m 1, or are they letters? e.g. -m L, etc?
Leaving -m says it requires an argument
TypeError: Image mode must be 'L', 'P', 'RGB' or 'CMYK' 
putting any of these does not solve the problem.

**Comment by grlee77** [comment]
I had missed this issue a while back.  The error you are seeing seems to be that `PIL` (or Pillow) is having a problem reading whatever image type you are using.  I don't think there as an issue with the command line arguments.

If you run the `image_blender.py -h` the values listed as "default" arguments indicate what is expected.  

Here is a simple nonsense example of applying a "fingerprint" texture to a color image of an airplane. 

```
python image_blender.py -b ~/airplane.ppm -t ~/fingerprint1.pgm -o blended.png -l 3 -w sym4 -m symmetric
```
input images were obtained from:  http://www.hlevkin.com/06testimages.htm

example output:
![blended](https://user-images.githubusercontent.com/6528957/36401202-d72968c6-15a3-11e8-9a38-3491791c1907.png)
