### ISSUE TITLE
Can't compile pywt

### ISSUE THREAD

**Issue by deltaxflux** [PyWavelets/pywt#343]
Hey guys,

I have following issue if I try to compile pywt. I works flawlessly in python3 but not for python2.
I get following trace:

```
Traceback (most recent call last):
  File "/bin/pip2", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/usr/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

I have a lack of time and I will improve this issue later.

Regards,

deltax

**Comment by rgommers** [comment]
That seems to be a PyInstaller related issue, also dependent on setuptools version. Try upgrading both of those

**Comment by deltaxflux** [comment]
@rgommers 

Thanks for your answer. In my case it was not caused by old python libraries. I fixed my environment after I force reinstall my packages.

## Method 1
* Reinstall the short way
```
sudo pacman -Qkq
```
but this doesn't work for me

## Method 2
* Deinstall all python2 packages
 ```
sudo pacman -Rdd $(pacman -Qqs python2)
```

 ```
sudo pacman -S python2 python2-pip
```

**Comment by rgommers** [comment]
Thanks @deltaxflux, closing this then
