### ISSUE TITLE
Add antisymmetric signal extension mode

### ISSUE THREAD

**Issue by zstomp** [PyWavelets/pywt#346]
It works well for me when I prepad my data when detrending with SWT/ISWT, but with DWT you can't unpad the result like with SWT.

**Comment by grlee77** [comment]
Sorry about taking so long to respond to this issue.  It should not be too difficult to add this edge mode and I can try to do so when I get a chance.  Looking at the Matlab docs online, I see that Matlab also offers whole and half-sample antisymmetric edge modes.

Out of curiousity, what is an example application when "anti-symmetric" is preferable?

**Comment by zstomp** [comment]
No problem, I realize this might be obsolete as there is `smooth`. However, in my experience with financial time series, antisymmetric is the best for detrending/denoising as it preserves edges nicely despite the irregular nature of the series. Now I'd like to see how it would behave in other parts of my financial analysis.

**Comment by grlee77** [comment]
Please see a proposed implementation in #351.  The mode `antireflect` (`asymw` in Matlab) sounds more like what you are describing (continuous first derivative at the boundary).  The other `antisymmetric` mode is likely to create discontinuities.

**Comment by zstomp** [comment]
Thank you so much! Yes, `antireflect` is my case. Oh, and the charts look just great!

**Comment by grlee77** [comment]
closed by #351
