### ISSUE TITLE
question: scaling like in IDL

### ISSUE THREAD

**Issue by iAnanich** [PyWavelets/pywt#347]
I want to build wavelet with scaling like in IDL 2004 (shown in picture):

![sample](https://user-images.githubusercontent.com/28541423/36324642-d6b02d5a-135d-11e8-99f1-c95bcdc6fb6b.png)

How to do that?

**Comment by grlee77** [comment]
Are you trying to do a power spectrum analysis with CWT?  Which scaling are you trying to get to match? (do you mean the "scale" units on the y axis here or are you referring to the magnitudes as in the colorbar?)

If you have not seen it already, the following demo gives an example usage that could probably be adapted to your use case.
https://github.com/PyWavelets/pywt/blob/master/demo/cwt_analysis.py

**Comment by iAnanich** [comment]
@grlee77 thanks for this demo! I meant Y-axis scaling.
