### ISSUE TITLE
citing PyWavelets

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#348]
A user on the mailing list recently [asked how best to cite PyWavelets](https://groups.google.com/forum/#!topic/pywavelets/OE-OeefLsrk).

 @PyWavelets/core: 
There is not currently a PyWavelets-specific journal article, but it would still be good to have a way for users to cite the software.  What do you think about making it citeable via something like [Zenodo](https://zenodo.org/)?  A nice feature there seems to be that you can have a top-level DOI that always references the current release or the user can cite a specific release.

Are there other alternatives that would be worth considering as well?

**Comment by rgommers** [comment]
Making every release have a DOI is a good idea, that can be done automatically with Zenodo. 

> Are there other alternatives that would be worth considering as well?

I think we should soon do a new release, and then write a JOSS (http://joss.theoj.org/) article. That takes about an hour, and ticks the boxes for a citable article. Helps giving academic credits to the people who have invested a lot of time in PyWavelets.

**Comment by rgommers** [comment]
I'll reply on the list with a citation suggestion for right now.

**Comment by grlee77** [comment]
I added this repository on Zenodo earlier in the week and it looks like it has successfully generated a DOI for the 1.0.0 release:
https://zenodo.org/record/1407172#.W4ms2RgnaDM

I update a few minor things like adding the license info that were not properly auto-detected. Please let me know if you notice anything else that looks out of place.

**Comment by rgommers** [comment]
LGTM. We could add the Zenodo badge in `README.rst`:
```
.. image:: https://zenodo.org/badge/DOI/10.5281/zenodo.1407172.svg
   :target: https://doi.org/10.5281/zenodo.1407172
```

(and maybe also TravisCI and Appveyor?)

**Comment by grlee77** [comment]
#419 adds various badges

**Comment by rgommers** [comment]
I think we can close this, all actions done except the JOSS submission - but no need for an issue for that.
