### ISSUE TITLE
FYI: PyWavelet does not correctly declare setup.py dependency on numpy

### ISSUE THREAD

**Issue by mickeyzoox** [PyWavelets/pywt#352]
See https://github.com/pypa/setuptools/issues/1281

According to benoit-pierre the solution is to just add a `setup_requires` dependency to `setup.py`, but have not tested.

**Comment by rgommers** [comment]
Thanks @mickeyzoox. This was fixed by gh-321, which will be in the next release. Note that that's a better fix than using `setup_requires`.
