### ISSUE TITLE
Calculating wavelet-coherence of two waves?

### ISSUE THREAD

**Issue by Losses** [PyWavelets/pywt#370]
Because some research requirement, I  need to calculate the wavelet-coherence of two waves. I've did a lot of search from the document site but find nothing, so, could PyWavelets finish this task, and if I would be grateful if some one could provide some link or example.

**Comment by Losses** [comment]
@grlee77 I also found pycwt but it did not provide any document of wavelet coherence, and the tutorial of pycwt is a little... confusing...
Wavelet coherence is a very important method for neuronscience, if pywavelets could add this method, it would be a great help :)
Thanks a lot for your timely reply.:smiley:

**Comment by grlee77** [comment]
A user recently posted an example to the mailing list that may be relevant:
https://groups.google.com/forum/#!topic/pywavelets/Nxn0DqVxBg4

**Comment by Losses** [comment]
@grlee77 Wow, thanks bro. It looks really good! I'll try to understand it and use it on my further project!

**Comment by rgommers** [comment]
The question was answered, I'll close this issue.
