### ISSUE TITLE
conda update requires downgrade of scipy

### ISSUE THREAD

**Issue by jslavin** [PyWavelets/pywt#372]
Hi,

I'm interested in using one of the newer wavelet forms included in pywavelets. It doesn't appear to exist in my current version (0.5.2).  However when I do 'conda update pywavelets' it gives me (clipped):

The following packages will be DOWNGRADED:

    blas:           1.1-openblas                  conda-forge --> 1.0-mkl              
    numpy:          1.13.3-py36_blas_openblas_201 conda-forge [blas_openblas] --> 1.13.3-py36ha266831_3
    scipy:          1.0.1-py36_blas_openblas_200  conda-forge [blas_openblas] --> 0.19.1-np113py36_0   

Proceed ([y]/n)? n

Any idea why scipy would need to be down downgraded from 1.0.1 to 0.19.1?

Jon

**Comment by grlee77** [comment]
If you are looking for things implemented more recently than the 0.5.2 release, those will not be on conda-forge which only packages the official releases.  To build from the latest master branch you would need to uninstall any existing conda package for PyWavelets  (`conda uninstall pywavelets`).  You can then download this source repository and build the package by running `pip install .` from within the root directory of the package (i.e. the location of setup.py).  You will need a C compiler, Cython and Numpy to build the package from source.

**Comment by jslavin** [comment]
Hi Gregory,

Thanks for your reply.  The information you provided, i.e. that pywavelets
doesn't depend on scipy, is important in this case.

Jon

**Comment by jslavin** [comment]
So 0.52 is the latest release?  That wasn't clear to me.  Is that listed
somewhere? I guess the fact that the only versioned branch is 0.5.x should
be a clue.

Jon

**Comment by rgommers** [comment]
It may be about time for a new release. @grlee77 will you be at the SciPy conference? Would be nice to meet up.

**Comment by grlee77** [comment]
Yes, I agree that we should do a new release soon and have some time to work on it.  If you are available to help finalize some things that would be great.

I just returned from an academic conference overseas and unfortunately couldn't fit scipy into my travel budget for this year. I can call in or connect remotely, though, if you want to chat. My schedule is pretty flexible.

**Comment by grlee77** [comment]
Also, a potential workaround to the problem in this PR is to pin numpy and scipy to the versions on conda-forge. At least on linux, this is done by adding lines such as the following to the `.condarc` file located in your home account:
```
pinned_packages:
  - conda-forge::numpy
  - conda-forge::scipy
```

I have seen this attempt to switch to MKL versions from defaults in the past in other contexts not related to PyWavelets and pinning seems to resolve it.

**Comment by rgommers** [comment]
I'm very busy till SciPy starts next Wednesday, but should have some bandwidth after that. How about we have a chat around July 15-18 and try to come up with a plan?

**Comment by rgommers** [comment]
I think there should be a better solution than pinning (not sure if there is one though). I've seen this `conda` downgrade stuff in a number of installs before, it's very annoying/confusing.....

**Comment by rgommers** [comment]
Talked to the `conda-forge` team, apparently there's no better solution for the time being. The issue is caused by the dependency resolver, which (among other things) tries to minimize the number of "features" used. OpenBLAS is a feature, so can be "optimized out", even if one doesn't request any package install related to MKL/OpenBLAS.
