### ISSUE TITLE
API issues to discuss or change

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#38]
This list is meant to keep track of things we come across in the API that don't look right and may need fixing (after completing the refactoring):

- function names in functions.py need to be longer and clearer (``intwave``, ``centrfrq``, ``scal2frq``, ``orthfilt``).
- ``qmf`` already exists in ``scipy.signal``
- ``wavelet`` parameter to functions should be uniform everywhere (can be Wavelet instance, string and in some cases ``intwave`` even a third option).
- functions in thresholding.py are (too?) simple and in two cases equal numpy names.
- ``MODES`` is all capitals. It's properties aren't very Pythonic.
- ``Wavelet`` has ``__str__`` but not ``__repr__``.

**Comment by aaren** [comment]
Closed by #55.
