### ISSUE TITLE
New warning appearing

### ISSUE THREAD

**Issue by jachymb** [PyWavelets/pywt#405]
I am getting this warning from pywt. It apparently has to do with me upgrading to a  most recent version of python/numpy.

`/usr/lib/python3.7/site-packages/pywt/_multilevel.py:148: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.`

**Comment by grlee77** [comment]
Hi @jachymb.  This warning occurs when PyWavelets is used with Numpy 1.15.  It has been fixed by #378 and #382 the master branch. We have plans to make a new PyWavelets release including this fix soon.
