### ISSUE TITLE
Issue using pywt

### ISSUE THREAD

**Issue by shervinazad** [PyWavelets/pywt#430]
Hello,
I am new to python. I have downloaded and install pywt using different approaches. I installed it in conda and add it as an interpreter in my pycharm as well. I can see it the lib folder but when I am calling dwt I am getting following error. Can you please let me how I can solve this issue?

    coeffs2 = pywt.dwt2(original, 'bior1.3')
AttributeError: module 'pywt' has no attribute 'dwt2'

**Comment by grlee77** [comment]
Is it possible you have installed [PyWT](https://pypi.org/project/PyWt/) which is actually a different package? `pip install pywt` would install that package and not PyWavelets, which is unfortunately an easy mistake to make. 

If so, I would try:
`pip uninstall pywt` followed by `pip install pywavelets` (or `conda install pywavelets` if you are using Anaconda Python)

I would guess that things would likely also be broken if you have both PyWT and PyWavelets installed simultaneously because they share the same module name.

**Comment by syfantid** [comment]
I am having the same issue. Initially I installed pywt, then uninstalled it and installed the correct package. I froze pip (requirements.txt) and only the latter package is included. However, I still get the same error.

**Comment by grlee77** [comment]
maybe there are still some residual files that did not get uninstalled?
What if you try:
```python
import pywt
print(pywt.__file__)
```

Does the path printed above contain files from the PyWT package instead PyWavelets? If so, it was somehow not uninstalled properly and you may need to manually remove that folder and then try installing PyWavelets again.

**Comment by grlee77** [comment]
alternatively, to print the files directly you can try
```
import os
import pywt
print(os.listdir(os.path.dirname(pywt.__file__)))
```

you should see something like:
```
['version.py',
 '_swt.py',
 'tests',
 '_dwt.py',
 '_wavelet_packets.py',
 'data',
 '_thresholding.py',
 '_multilevel.py',
 '_cwt.py',
 '_extensions',
 '_doc_utils.py',
 '__pycache__',
 '_multidim.py',
 '_functions.py',
 '_utils.py',
 '__init__.py',
 '_c99_config.py']
```
as the output of that command.

**Comment by syfantid** [comment]
Yeah, it was probably some residual files despite the uninstall of pywt. I recreated the project with the correct dependencies and it works now. Thanks!

**Comment by renatosc** [comment]
Same issue here, but with the error:

> AttributeError: module 'pywt' has no attribute 'dwt2'

I had to uninstall **pywt** and restart my jupyter kernel. Now it works.

**Comment by Afrahnaeem** [comment]
from pywt import wavedec

ImportError: cannot import name 'wavedec' from 'pywt' (C:\Users\Afrah\Anaconda3\lib\site-packages\pywt\__init__.py)

i am also facing same trouble... I tried to solve this issue with all of the solutions mentioned above.. but it did not help me out.. Kindly suggest me any other solution to resolve this.

**Comment by grlee77** [comment]
If you try the comands in [this comment](https://github.com/PyWavelets/pywt/issues/430#issuecomment-470173497), are you seeing those PyWavelets files as expected?

I am not sure how you are trying to install (pip vs. conda), but I think in some cases you might have to run `pip uninstall pywt` more than once. I would manually inspect your Python site-packages folder and check for any other traces of the PyWT package that might need to be removed prior to reinstalling PyWavelets. 

Make sure you are installing pywavelets via `pip install pywavelets` and NOT `pip install pywt`.
