### ISSUE TITLE
Documentation Issue: instructions for installing from source not working

### ISSUE THREAD

**Issue by cgoldberg** [PyWavelets/pywt#437]
There are several suggestions in the project code and docs to install from source using **`pip install .`**.  However, attempting to install from current master branch on my Linux system left me with a broken `pywt` package.  Installation appeared to complete successfully, but I was unable to `import pywt` afterwards:

```
>>> import pywt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cgoldberg/code/pywt/pywt/__init__.py", line 16, in <module>
    from ._extensions._pywt import *
ImportError: No module named 'pywt._extensions._pywt'
```

System info: Ubuntu 16.04, Python 3.5. virtualenv with all build dependencies installed.

The solution for me was to do an "editable" install of pywt.  So, instead of of `pip install .`, I ran `pip install -e .` and everything works fine.  I'm not quite sure why an editable build is necessary, but perhaps the docs should recommend this?

----

Note: references to running `pip install .` appear in:

 * README.rst
 * setup.py (in 2 places)
 * doc/source/install.rst

I also noticed the instructions from the Development Guide for installing from source seem to work. (but they don't recommend `pip install .`)

**Comment by rgommers** [comment]
If `pip install .` doesn't work, that's a serious bug. Can you provide the full build log? And what `pip` version is that?

**Comment by cgoldberg** [comment]
> Can you provide the full build log?

Below is a complete transcript of my build/install from source.  You can see that after a seemingly successful pywt installation into a fresh virtualenv, I am unable to import it.

> And what pip version is that?

18.1 (the latest)
 
```
$ git clone https://github.com/PyWavelets/pywt
Cloning into 'pywt'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 8906 (delta 11), reused 14 (delta 6), pack-reused 8872
Receiving objects: 100% (8906/8906), 12.82 MiB | 8.60 MiB/s, done.
Resolving deltas: 100% (6296/6296), done.
Checking connectivity... done.
$ cd pywt
$ python3 -m venv ENV
$ source ENV/bin/activate
(ENV) $ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 1.4MB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-18.1
(ENV) $ pip install cython
Collecting cython
  Downloading https://files.pythonhosted.org/packages/88/63/e844d2e35ad3b97e14b7549030719baa4eb6c4c8c4ef0a844e4ba4cf10e2/Cython-0.29.1-cp35-cp35m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 8.6MB/s 
Installing collected packages: cython
Successfully installed cython-0.29.1
(ENV) $ pip install .
Processing /home/cgoldberg/code/pywt
Collecting numpy>=1.13.3 (from PyWavelets==1.1.0.dev0+1c1d83f)
  Downloading https://files.pythonhosted.org/packages/86/04/bd774106ae0ae1ada68c67efe89f1a16b2aa373cc2db15d974002a9f136d/numpy-1.15.4-cp35-cp35m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 3.5MB/s 
Installing collected packages: numpy, PyWavelets
  Running setup.py install for PyWavelets ... done
Successfully installed PyWavelets-1.1.0.dev0+1c1d83f numpy-1.15.4
(ENV) $ python3 -c "import pywt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cgoldberg/code/pywt/pywt/__init__.py", line 16, in <module>
    from ._extensions._pywt import *
ImportError: No module named 'pywt._extensions._pywt'
```

---

Also, here is the output of some commands I ran afterwards to show more of my system info and build environment:

```
(ENV) $ pip freeze
Cython==0.29.1
numpy==1.15.4
pkg-resources==0.0.0
PyWavelets==1.1.0.dev0+1c1d83f
(ENV) $ pip --version
pip 18.1 from /home/cgoldberg/code/pywt/ENV/lib/python3.5/site-packages/pip (python 3.5)
(ENV) $ easy_install --version
setuptools 20.7.0 from /home/cgoldberg/code/pywt/ENV/lib/python3.5/site-packages (Python 3.5)
(ENV) $ git status | grep branch
On branch master
Your branch is up-to-date with 'origin/master'.
(ENV) $ git rev-parse --short HEAD
1c1d83f
(ENV) $ python3 --version
Python 3.5.2
(ENV) $ lsb_release --description
Description:    Ubuntu 16.04.5 LTS
(ENV) $ uname --all
Linux collosus 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(ENV) $ gcc --version | grep gcc
```

---

HTH,
-Corey

**Comment by rgommers** [comment]
Sorry, I wasn't specific enough. `Running setup.py install for PyWavelets ... done` is not quite detailed enough to see what's going on. Could you try `pip install . -v`? (that's verbose mode, it will show the full build output.

**Comment by cgoldberg** [comment]
[build.log](https://github.com/PyWavelets/pywt/files/2612691/build.log)

**Comment by rgommers** [comment]
Thanks. The issue is simply that you try to import `pywt` from the wrong place. The extension is installed:

     copying build/lib.linux-x86_64-3.5/pywt/_extensions/_pywt.cpython-35m-x86_64-linux-gnu.so -> /home/cgoldberg/code/pywt/ENV/lib/python3.5/site-packages/pywt/_extensions

Note it goes into `code/pywt/ENV/`. Now note your import error, it imports `code/pywt/pywt/__init__.py`. That is because you're trying 

    (ENV) $ python3 -c "import pywt"

from the root of the `pywt` repo, and it tries to import the repo version rather than the version you installed into `ENV.` Just do `cd ../..` or something, and things will work.

**Comment by cgoldberg** [comment]
¯\_(ツ)_/¯ doh!  ... now I feel dumb :)
My apologies for wasting your time.  Thanks much for investigating this!

**Comment by rgommers** [comment]
no worries
