### ISSUE TITLE
Issue using pywt.WaveletPacket2D

### ISSUE THREAD

**Issue by HEIDIES** [PyWavelets/pywt#447]
Hello,
A coefficients size error occured on using reconstruct method of waveletpacket2d. My codes are:
`original = pywt.data.camera()`
`wp = pywt.WaveletPacket2D(data=original, wavelet='db3', mode='smooth', maxlevel=3)`
`print(wp['aaa'].data.shape)`
`print(wp['aav'].data.shape)`
`print(wp['aah'].data.shape)`
`print(wp['aad'].data.shape)`
`wp.reconstruct()`

And:
> ValueError: `coeffs` must all be of equal size (or None)

Basically, since I used the coefficients of level 3 by path, these four coefficients would be the leaf nodes. The coefficients wp['aa'] would be reconstructed by wp['aaa'], wp['aav'], wp['aah'], and wp['aad'], and wp['av'], wp['ah'], wp['ad'] would still be the leaf nodes. But problem here is, the shape of wp['aa'] is not equal to either the shape of wp['av'], wp['ah'] or wp['ad'], the former one is reconstructed by its child nodes, and the latter three are directly decomposed from original image. Is there any shape conditions of using waveletpacket2d?

**Comment by grlee77** [comment]
This is a bug. I think I have a local branch where I had fixed this. Let me find it and make a PR.

**Comment by grlee77** [comment]
A fix for the issue has been proposed in #448
