### ISSUE TITLE
Coefficients arrays must have the same dtype error in iswt function

### ISSUE THREAD

**Issue by tallamjr** [PyWavelets/pywt#449]
Within `iswt(coeffs, wavelet)` function of `pywt/pywt/_swt.py` there is a `dtype` check for cD coefficients but not for cA coefficients.

In the following line:
```
dt = _check_dtype(cD)
cD = np.asarray(cD, dtype=dt)
```
The `dtype` is set for cD's but there is not setting for cA's also. 

This has the effect of when running something which changes the type of cD, cA's then become of a different `dtype` and gives the following error: 
`ValueError: Coefficients arrays must have the same dtype`

**Comment by grlee77** [comment]
Thanks for reporting this. I can reproduce the issue. It seems `dwt`/`idwt` does support this so it makes sense to do the same for `swt`/`iswt` as well.

I made a PR extending mixed precision coefficient support to more inverse transforms in #450.
