### ISSUE TITLE
Independent test comparison

### ISSUE THREAD

**Issue by Dapid** [PyWavelets/pywt#46]
I think this belongs to a new issue.

Right now, the test suite is (roughly) ensuring the results are the same as they were in the last published version of pywt. I think the values we get should be compared to other completely independent implementations. [R has several](http://stackoverflow.com/questions/3363826/best-wavelet-library-for-r) libraries we could use, and there is also the MATLAB comparison.

I don't speak R nor have MATLAB installed, but if you could compile a Windows release, I can ask people to run it for me.

I will poke around to see if anyone has MATLAB on Linux, though.

**Comment by rgommers** [comment]
This is now addressed by easier testing against the results from Matlab, which are now also stored in the repo. See gh-100.
