### ISSUE TITLE
Consider migrating to non-fork repository

### ISSUE THREAD

**Issue by zbeekman** [PyWavelets/pywt#466]
Forks are great, but by default GitHub does not index them for searching. You might want to consider migrating this repo to a non-fork version. It will be a pain to deal with the issues, wiki, project, etc. but IMO, worth it. Forks do not work well for main projects.

**Comment by rgommers** [comment]
fair enough, it's about time for that. looks like there's no way to do that other than contacting Github support: https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by grlee77** [comment]
@rgommers: Do you want me to go ahead and write to GitHub and ask them to do this? I didn't want to do it while I was finalizing the 1.0.2 release, but can try it now.

GitHub's docs say:

>> If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network.

I assume we want to move these forks as well?  For example my grlee77/pywt repo is forked from PyWavelets/pywt (and not nigma/pywt), so hopefully it would continue to just work without having to fork again after the conversion.

**Comment by rgommers** [comment]
Yes that would be great. Thanks!

> I assume we want to move these forks as well?

yes all forks should be moved, even the ones that were originally forked from `nigma` if that's possible. That repo is no longer active, so not much point having forks of it.

**Comment by grlee77** [comment]
Okay, I just sent them a request to make this a standalone repository.

**Comment by grlee77** [comment]
I got a message from GitHub today confirming that they have detached this repo from nigma/pywt.  Thanks for raising the issue @zbeekman
