### ISSUE TITLE
pywt wheels need to be rebuilt with newer cython version

### ISSUE THREAD

**Issue by nils-werner** [PyWavelets/pywt#467]
In Python 3.7 an `ImportWarning` will be issued when importing pyWt:

    import pywt
    ../lib/python3.7/site-packages/pywt/__init__.py:16: in <module>
    from ._extensions._pywt import *
    pywt/_extensions/_pywt.pyx:1: in init pywt._extensions._pywt
    ???
    pywt/_extensions/_dwt.pyx:7: in init pywt._extensions._dwt
    ???
    ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__

In my case it is tripping up pytest, which makes an error out of this warning, making the testsuite on my library fail.

As this issue is related to [this one](https://github.com/aio-libs/multidict/issues/304) a workaround is to simply rebuild pywt from source, with an appropriately recent version of cython:

    pip uninstall PyWavelets
    pip install "cython>=0.29.0"
    pip install -U --no-binary :all: PyWavelets

And as a final solution, the wheels should be rebuilt with this cython version.

**Comment by grlee77** [comment]
Thanks for raising the issue.
We have been planning to do a 1.0.2 bug fix release very soon (possibly even later this evening). The new wheels should get built with the latest Cython, so hopefully that will fix the issue.

**Comment by grlee77** [comment]
Closing this now that PyWavelets 1.0.2 has been released. Please reopen if you still encounter the issue.
