### ISSUE TITLE
add an equivalent of Matlab's wextend?

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#473]
Matlab provides a function called `wextend` for padding a signal via the various boundary modes. In PyWavelets, the signal is not explicitly extended, but for efficiency the [boundary modes are handled in the C convolution code](https://github.com/PyWavelets/pywt/blob/2e3a224a4600a07feb2c88e62c2ecdadfbc63f2b/pywt/_extensions/c/convolution.template.c#L153-L219).

However, I already implemented a [function that replicates the behavior](https://github.com/PyWavelets/pywt/blob/2e3a224a4600a07feb2c88e62c2ecdadfbc63f2b/pywt/_doc_utils.py#L152) of `wextend` in 1D for the purpose of making a nice figure of the various boundary modes for the documentation.

Updating the existing, non-public `pywt._doc_utils.pad` function to be n-dimensional andexposing it under the name `pywt.wextend` should be fairly straightforward.

I'm not sure how common use of `wextend` would be, but I did notice that the implementation of wavelet adjoints linked in #472 makes use of it.

**Comment by rgommers** [comment]
I think that makes sense, could be a useful function. `wextend` is a pretty bad name though (as usual in Matlab), why not just call it `pad`?
