### ISSUE TITLE
Continous wavelet transform?

### ISSUE THREAD

**Issue by Dapid** [PyWavelets/pywt#48]
There is an experimental branch using cwt:

https://bitbucket.org/nigma/pywt/src/89b218002904

We should fix it and merge it. It is not on the Github repository, though.

**Comment by cdeil** [comment]
I'd also be *very* interested in having CWT functionality available in `pywt`.

In Gammapy we had this as a contribution:
https://github.com/gammapy/gammapy/blob/master/gammapy/detect/cwt.py#L50
I know very little about wavelets, but I think the only application-specific things like what are significant coefficients could be factored out, and a more generic CWT function or class could be provided to make the implementation of such use cases easier?

**Comment by grlee77** [comment]
CWT added by #172

**Comment by cdeil** [comment]
Is the CWT functionality mentioned in the docs?

I can't find it:
http://pywavelets.readthedocs.io/en/latest/search.html?q=cwt&check_keywords=yes&area=default

**Comment by cdeil** [comment]
Forgot to say: thank you very much for adding it!

**Comment by rgommers** [comment]
@cdeil that search for ``cwt`` should give you some results in the docs now.

**Comment by cdeil** [comment]
@rgommers Thanks!
