### ISSUE TITLE
wavelet coefficient of spectra of graph

### ISSUE THREAD

**Issue by MDARQUAM** [PyWavelets/pywt#480]
Hi,
Please help me to calculate the wavelet coefficient of spectra of the graph.

**Comment by grlee77** [comment]
Are you referring to the "spectral graph wavelet transform"? We do not have any functions in PyWavelets for operating on non-uniformly spaced samples or graphs. 

Perhaps this demo from the Python Spectral Graph Processing library corresponds to what you want?: 
https://pygsp.readthedocs.io/en/stable/tutorials/wavelet.html

**Comment by rgommers** [comment]
Question was answered, closing.
