### ISSUE TITLE
swt decomposition without all the coarse levels

### ISSUE THREAD

**Issue by zaccharieramzi** [PyWavelets/pywt#489]
In the [current implementation of the `swt`](https://pywavelets.readthedocs.io/en/latest/ref/swt-stationary-wavelet-transform.html#multilevel-1d-swt), the function returns all the coarse levels (called here approximation). But I think we only need the last one theoretically. 

Indeed, when looking at [the code](https://github.com/PyWavelets/pywt/blob/master/pywt/_swt.py#L133), you can see that the approximation coefficients are discarded and when only keep the detail coefficients for reconstruction. The last coarse level is safely saved [here](https://github.com/PyWavelets/pywt/blob/master/pywt/_swt.py#L118). I think it would be nice if there was an option to decompose/reconstruct without all these additional coefficients.

**Comment by grlee77** [comment]
Agreed. This feature was recently proposed in #476 if you have any feedback to add there in terms of how you would like it to look.

**Comment by zaccharieramzi** [comment]
No, I think from what I saw it was what I had in mind. Cool that you were working on this!
