### ISSUE TITLE
warnings module used in setup.py but never imported

### ISSUE THREAD

**Issue by zerothi** [PyWavelets/pywt#494]
Title says it all,

you have a `warnings.warn` in your `setup.py` but nowhere is the package loaded!

This is a build bug in 1.0.3 which makes `pip` fail in some cases...

**Comment by grlee77** [comment]
Thanks for reporting this! It is being addressed in #495

**Comment by zerothi** [comment]
Great, I thought creating a pr was too much of a hazzle :)

I'll close since it is already merged.
