### ISSUE TITLE
Errors in time series 

### ISSUE THREAD

**Issue by GlennCloser** [PyWavelets/pywt#497]
The software seems to be unable to run wavelet transformations on time series.   All the examples in the manual reference short arrays of just a few numbers.   The time series I am working with run to about 9,500 to 11,500 observations.   The major problem is that Python always responds with an error message that is flagrantly incorrect.   I uploaded the data, and converted from string to integer format.   Testing the data repeatedly shows that it is in integer or float format, not in string format.   However, every time I run a wavelet command, Python responds:

ValueError: could not convert string to float: 'V1' 

For example, the input line is:
pywt.cwt('V1', 1, 'db2')    where V1 is a time series in integer format.   Python always responds:
ValueError: could not convert string to float: 'V1' 

So I tried including the dataframe:
pywt.cwt(VBase['V1'], 1, 'db2')
Python responds with an equally incomprehensible error message:
AttributeError: 'pywt._extensions._pywt.Wavelet' object has no attribute 'complex_cwt'

Does anyone have some sample code which can be used to calculate wavelet decompositions for time series?

- Glenn

**Comment by grlee77** [comment]
Hi @GlennCloser 
The first case where you are passing a string 'V1' as the input will not work. You need to specify an array (or array-like object such as a list). There will should not be a problem processing much larger timeseries with thousands to millions of samples.

It looks like you did pass an array for the first input in your second call. The error there is that the wavelet name you specified is only available for discrete transforms (this is why it is missing the `complex_cwt` attribute that the error message mentions). For the function `cwt`, you have to use one of the continuous wavelets defined at:
https://pywavelets.readthedocs.io/en/latest/ref/cwt.html#continuous-wavelet-families

If you want to do discrete wavelet decomposition with 'db2' you should look at the functions `wavedec` or `swt`, which perform discrete wavelet transforms. In the case of `swt` this is done without downsampling so that the transform is shift-invariant.

Aside from the minimal examples in the docstrings, there are some examples of usage available in the scripts located at:
https://github.com/PyWavelets/pywt/tree/master/demo

**Comment by grlee77** [comment]
Actually, on second thought, perhaps the `cwt` function is intended to allow also calling it with any of the discrete wavelets as well. At least the following line seems to indicate this is the case:
https://github.com/PyWavelets/pywt/blob/fa2eee11c856d5a9eb5497012e481b4882c2c150/pywt/_cwt.py#L73

In that case we just need to make a one line change at:
https://github.com/PyWavelets/pywt/blob/fa2eee11c856d5a9eb5497012e481b4882c2c150/pywt/_cwt.py#L78

to be
```Python
if isinstance(wavelet, ContinuousWavelet) and wavelet.complex_cwt:

I am not sure if there are cases where these discrete wavelets are preferable to the various continuous ones when running a CWT, though?

**Comment by GlennCloser** [comment]
First, thank you for the advice.   I was able to convert the data to an array format, and run the 
decomposition.   The following code ran perfectly.     


w = pywt.Wavelet('db2')
(a, d) = pywt.dwt(VBase['VTSI2'], wavelet=w, mode='smooth')
print (a)
print (d)
print(pywt.idwt(a, d, 'db2', 'smooth'))

Two questions.  First, how would I export the coefficient arrays a and d to Excel, or CSV?  Similarly, how would I export the reconstructed series to CSV?    

More importantly, I tried something a multilevel decomposition, which is right out of page 68 in the manual:
(a, b, c, d) = pywt.dwt(VBase['VDEV2'], 'db4', 'smooth')

The system returned the following error:
ValueError: not enough values to unpack (expected 4, got 2)
What is the problem here?  I set up four coefficient arrays, just as in the manual.  Why is the system responding that it got 2?

**Comment by GlennCloser** [comment]
Actually, the question above is too specific.   The number of components in the time series I am analyzing is on the order of 6-7, including low, intermediate and high frequency.   Fourier waves don't work because the impulses are discontinuous.   In effect, what I need to do is decompose this data set into about 6 components.   The code in the manual seems based on the idea of two components, high and low frequency.   Can anyone provide some simple code to create six rather than two coefficient arrays?

**Comment by grlee77** [comment]
> Two questions. First, how would I export the coefficient arrays a and d to Excel, or CSV? Similarly, how would I export the reconstructed series to CSV?

To write to Excel or CSV, I would recommend using Pandas. Store your arrays in a Pandas DataFrame and then use the `to_excel` or `to_csv` method: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html
There is also a `csv` module in Python's standard library, but I think the Pandas approach should be easier.

If you just want to write a single array to CSV you could also use NumPy's [savetxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html), setting `delimiter=','.:

**Comment by grlee77** [comment]
> More importantly, I tried something a multilevel decomposition, which is right out of page 68 in the manual:
(a, b, c, d) = pywt.dwt(VBase['VDEV2'], 'db4', 'smooth')

Do you have a link to where you are seeing this notation? If that exact form is in the documentation, it should be fixed.

There should always only be two arrays returned by `dwt`. You would get four arrays if you ran a three level transform via `wavedec`:
```Python
(cA3, cD3, cD2, cD1) = pywt.wavedec(VBase['VDEV2'], 'db4', mode='smooth', level=3)
```

**Comment by grlee77** [comment]
> In effect, what I need to do is decompose this data set into about 6 components. The code in the manual seems based on the idea of two components, high and low frequency. Can anyone provide some simple code to create six rather than two coefficient arrays?

You can do this with `pywt.swt` or `pywt.wavedec` with `level=5` to get 1 approximation and 5 detail coefficient arrays. Each subsequent level divides the lowpass band from the previous level in two.

You might also consider looking at `pywt.WaveletPacket` class which can be used to filter both the low and highpass bands at each level, creating a finer frequency division. It is a little more complicated to work with than the `swt` or `wavedec` functions, though. 

Another transform that might possibly be of interest is the short time Fourier transform (`stft`) which is [available in SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html):

**Comment by rgommers** [comment]
The questions were answered, and the manual in question is not our docs - I'll close this issue.
