### ISSUE TITLE
replace cameraman image due to an uncertain rights

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#500]
See scikit-image/scikit-image#3927 on the uncertain rights to this image. We may need to replace it with a suitably licensed alternative.

It looks like our copy was obtained from scikit-image (added in #144)

**Comment by rgommers** [comment]
Oh fun. I agree, better to replace it even if in practice no one is going to complain.

**Comment by grlee77** [comment]
A big thanks to @stefanv for following up on this with MIT. It appears it should be okay to keep using it! (reference: https://github.com/scikit-image/scikit-image/issues/3927#issuecomment-538562885)

**Comment by grlee77** [comment]
Reopening as MIT eventually clarified that the cameraman image as returned by `pywt.data.camera()` requires a "non-commercial" clause. I will open a PR to replace it with a CC0 licensed variant as in scikit-image/scikit-image#3927
