### ISSUE TITLE
How to implement Matlab's wrcoef function?please

### ISSUE THREAD

**Issue by yanzhenxiong** [PyWavelets/pywt#503]
Like this:
[C,L]=wavedec(s,3,'db1');
A3=wrcoef('a',C,L,'db1',3); 
D3=wrcoef('d',C,L,'db1',3);
D2=wrcoef('d',C,L,'db1',2);
D1=wrcoef('d',C,L,'db1',1); 
How to implement  Matlab's wrcoef() function?

**Comment by holgern** [comment]
You can find an implementation here:
https://stackoverflow.com/questions/45051106/multilevel-partial-wavelet-reconstruction-with-pywavelets

**Comment by rgommers** [comment]
Question is answered, so I'll close this issue.
