### ISSUE TITLE
Data with an axis of length of 0 infinite loops

### ISSUE THREAD

**Issue by coderforlife** [PyWavelets/pywt#505]
Seems that if you gives the function an array where one of the axes lengths is 0 then the program goes into an infinite loop. The simple test case I found is:

```
dwtn([[]], 'haar')
```

But it is likely true about others as well, just haven't tested other situations.

**Comment by grlee77** [comment]
Thanks for reporting this. It looks like we need to add some kind of sensible error in this case. 

I don't believe we currently have any length 0 test cases.

**Comment by coderforlife** [comment]
I accidentally did it while writing in an IPython notebook. It was an incomplete line and then I lost my session when I killed the process (not really much of a loss).

**Comment by grlee77** [comment]
Okay, this should be addressed by #506.  There was a guard against this in the 1D case, but it was not being applied for >=2D data.

**Comment by coderforlife** [comment]
Great!
