### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections'

### ISSUE THREAD

**Issue by PeterNgTr** [PyWavelets/pywt#519]
I'm using this lib https://github.com/scikit-image/scikit-image and noticing the exposed deprecation warning like this from pywt.

```
/usr/local/lib/python3.7/site-packages/pywt/_utils.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable
```

**Comment by grlee77** [comment]
I think this was already addressed in #436.  I hope to make a 1.1 release in the coming weeks that would include this fix.
