### ISSUE TITLE
plans for 1.1 release

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#520]
Now that Python 3.8 is nearing final release, we need to make an official release here that incorporates the import fix from #436.

While we could do a 1.0.4 release just to include this fix, I think we have enough new things to go ahead with a 1.1 release. 

There are only three open PRs marked 1.1:
#439: I want to get this bug fix merged. It is nearly there and I can help finish it soon.
#395 has not been updated recently and can be pushed back
#478 it is ready if anyone gets a quick chance to review, but not a big deal to push back if not

Other open issues are potentially removing the cameraman image and potentially adding a code of conduct. I don't think either of those necessarily should block a release, though.

**Comment by rgommers** [comment]
All sounds good to me. CoC would be good; don't really care about the cameraman image, no one is complaining about that one. I'll have a look at gh-478.

**Comment by grlee77** [comment]
If we have PyWavelets follow the recommendations in [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html), it looks like we would drop Python 3.5 support from the 1.1.0 release. I don't have a strong opinion either way on dropping it now or soon after the release.

**Comment by rgommers** [comment]
Perhaps good to drop it straight after v1.1.0, to not leave scikit-image or other downstream hanging.

**Comment by grlee77** [comment]
Trying out wheel building over at MacPython/pywavelets-wheels#9

Once that is working, I think we should be ready to tag 1.1.0.

**Comment by rgommers** [comment]
old issue, closing.
