### ISSUE TITLE
DeprecationWarning over invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [PyWavelets/pywt#541]
I guess these files are used for CI and not for actual use of the package but I thought it would be good to file them in case of future errors from these deprecation. Feel free to close this if it's irrelevant.

```
./util/gh_lists.py:52: DeprecationWarning: invalid escape sequence \s
  title = re.sub(u"\s+", u" ", issue.title.strip())
./util/gh_lists.py:54: DeprecationWarning: invalid escape sequence \s
  remainder = re.sub(u"\s.*$", u"...", title[60:])
./util/refguide_check.py:498: DeprecationWarning: invalid escape sequence \w
  regex = ('[\w\d_]+\(' +
./util/refguide_check.py:499: DeprecationWarning: invalid escape sequence \w
  ', '.join(['[\w\d_]+=(.+)']*num) +
./util/refguide_check.py:500: DeprecationWarning: invalid escape sequence \)
  '\)')
```

**Comment by rgommers** [comment]
Thanks @tirkarthi. Indeed these are not part of the package. I don't see these warnings with Python 3.9, so I prefer to just close this issue and only deal with it in case something breaks in the future.
