### ISSUE TITLE
inversion problem

### ISSUE THREAD

**Issue by Navids71** [PyWavelets/pywt#542]
hello my friend, I have some problem 

in my case I have to use pywt.downcoef, butI don't know what is the inversion code for reconstructing back my signal, I mean how can I reconstruct my signal with only using the approximation coefficients through your package? does your package have any inverse function for that? I mean pywt.idowncoef or something like that?

sincerely

**Comment by mattbit** [comment]
> I mean how can I reconstruct my signal with only using the approximation coefficients through your package? does your package have any inverse function for that? I mean pywt.idowncoef or something like that?

I guess `pywt.upcoef` ([docs](https://pywavelets.readthedocs.io/en/latest/ref/idwt-inverse-discrete-wavelet-transform.html#pywt.upcoef)) is what you're looking for.

**Comment by rgommers** [comment]
Question was answered, closing this issue.
