### ISSUE TITLE
Synchrosqueezing: requesting reviewers

### ISSUE THREAD

**Issue by OverLordGoldDragon** [PyWavelets/pywt#543]
I am porting MATLAB's [Synchrosqueezing Toolbox](https://www.mathworks.com/help/wavelet/gs/wavelet-synchrosqueezing.html) to Python, and need reviewers; an eventual goal is a PR to PyWavelets, and this feature was [requested](https://github.com/PyWavelets/pywt/issues/258). Repository: [ssqueezepy](https://github.com/OverLordGoldDragon/ssqueezepy).

I lack almost any understanding of synchrosqueezing, thus my ability to design unit tests and proofread the original source code is limited; as such, someone with a familiarity w/ synchrosqueezing is desired. I've already made numerous corrections, but many remain.

The README is concise and descriptive, see for details. Anyone willing is free to make PR's and open Issues on the repository. I welcome any collaborators.

**Comment by grlee77** [comment]
We cannot directly port MATLAB code because it is not open source, but it appears that in this case you are not working from their commercial implementation, but instead from: https://github.com/ebrevdo/synchrosqueezing?

If so, it seems okay to me as that code is BSD licensed.

I can take a look to give some initial feedback, but it may be a week or so.

**Comment by gcrau** [comment]
Happy to test the outcome using my [dataset](https://github.com/PyWavelets/pywt/issues/258#issuecomment-269713638)

**Comment by OverLordGoldDragon** [comment]
@grlee77 Indeed, it's from the Git repo. And sounds good - I look forward to your review.

**Comment by OverLordGoldDragon** [comment]
If I were to give priority to any specific function, it'd be [synsq_cwt_fwd](https://github.com/OverLordGoldDragon/ssqueezepy/blob/master/ssqueezepy/synsq_cwt.py#L12), as it's the one I use in my immediate application, and has the closest agreement with paper results.

**Comment by grlee77** [comment]
I have left a few initial comments in your repository: OverLordGoldDragon/ssqueezepy#1

It looks like you are off to a good start in porting the Matlab toolbox.

Probably the primary issue to address in terms of integrating the code into PyWavelets itself would be:

1.) Can get a good result when reusing the CWT that is already in PyWavelets (and if not, why?). Ideally, we would prefer not to have a another duplicate CWT implementation to maintain.

Once the above issue is resolved, I would start out here with an initial PR containing perhaps just `synsq_cwt_fwd` and supporting functions. It is a bit easier to comment on PRs in GitHub than in a base repository due to the built in review functionality.

**Comment by OverLordGoldDragon** [comment]
@grlee77 Agreed on both the PR and PyWavelets' CWT; will do. Also fair regarding `opts`, though I find it better to keep some common and reasonably defaulatble arguments in `**kwargs` to avoid clutter; the docstring will list them all.

To notify, though, unsure when I'll resume working on the repo, as I realized a bit late that the `synsq_cwt_fwd` transform upsamples by anywhere from **250x to 1000x** - which breaks the deal for my 60GB dataset (--> 15-60TB), so I won't have any use for it.

**Comment by OverLordGoldDragon** [comment]
@grlee77 Figured a viable dim-reduction to offset the upsampling - so I'm back in the game. 

Will focus on the CWT case. [`pywt.cwt`](https://github.com/PyWavelets/pywt/blob/master/pywt/_cwt.py#L37) vs. [`cwt_fwd`](https://github.com/OverLordGoldDragon/ssqueezepy/blob/master/ssqueezepy/wavelet_transforms.py#L389) results & code below. Latter involves a preprocessing step which I've reproduced prior to feeding to former. The two are more similar than not, but differences remain significant. 

Relevant portions of source code differ notably, though as I'm unfamiliar with relevant concepts (wavelet transforms, etc), can't say much further. It seems, however, that `cwt_fwd` differs from `pywt.cwt` in concept, not implementation bug - in which case `cwt_fwd` will need to be added to PyWavelets for synchrosqueezing.

<hr>

**Observations**:

  - `cwt_fwd` has an imaginary component, `pywt.cwt` doesn't
  - `pywt.cwt`'s norm is ~10x greater (see `norm_abs`)
  - The signal (`x`) preprocessing seems to undo itself in this case as evident in vs. Unprocessed
  - `pywt.cwt` handles the noisy signal (`sN`) case considerably differently in the upper-half

<hr>

<details>
  <summary>Source code</summary>

```python
import numpy as np
import matplotlib.pyplot as plt
import pywt

from ssqueezepy.wavelet_transforms import cwt_fwd
from ssqueezepy.utils import padsignal
np.random.seed(0)


def viz_signal(t, s, sN, s1, s2, s3):
    _, axes = plt.subplots(1, 3, sharey=True, figsize=(10, 3))
    axes[0].plot(t, s1)
    axes[1].plot(t, s2)
    axes[2].plot(t, s3)
    plt.subplots_adjust(left=0, right=1, bottom=0, top=1, wspace=0, hspace=0)
    plt.show()

    _, axes = plt.subplots(2, 1, sharex=True, figsize=(10, 5))
    plt.subplots_adjust(left=0, right=1, bottom=0, top=1, wspace=0, hspace=0)
    axes[0].plot(t, s)
    axes[1].plot(t, sN)
    plt.show()

def _get_norm(data, norm_rel, norm_abs):
    if norm_abs is not None and norm_rel != 1:
        raise ValueError("specify only one of `norm_rel`, `norm_abs`")

    if norm_abs is None:
        vmax = np.max(np.abs(data)) * norm_rel
        vmin = -vmax
    else:
        vmin, vmax = norm_abs
    return vmin, vmax

def _make_plots(*data, cmap='bwr', norm=None, titles=None, suptitle=None):
    vmin, vmax = norm or None, None
    for x in data:
        print(x.shape)
    _, axes = plt.subplots(1, len(data), sharey=True, figsize=(11, 4))
    plt.subplots_adjust(left=0, right=1, bottom=0, top=1, wspace=.1, hspace=0)
    if suptitle is not None:
        plt.suptitle(suptitle, weight='bold', fontsize=13, y=1.1)

    for i, x in enumerate(data):
        axes[i].imshow(x, cmap=cmap, aspect='auto', vmin=vmin, vmax=vmax)
        axes[i].invert_yaxis()
        axes[i].set_title(titles[i], fontsize=14, weight='bold')
    plt.show()

def viz_compare(x1, x2, cmap='bwr', norm_rel=1, norm_abs=None, suptitle=None):
    vmin, vmax = _get_norm(np.real(x1), norm_rel, norm_abs)
    _make_plots(np.real(x1), np.real(x2), cmap=cmap,
                norm=(vmin, vmax), titles=("s", "sN"), suptitle=suptitle)

def viz_re_im(x, cmap='bwr', norm_rel=1, norm_abs=None, suptitle=None):
    vmin, vmax = _get_norm(np.real(x), norm_rel, norm_abs)
    _make_plots(np.real(x), np.imag(x), cmap=cmap,
                norm=(vmin, vmax), titles=("Real", "Imag"), suptitle=suptitle)


def _pre_pywt_cwt(x, opts, nv=32, dt=1):
    opts = opts.copy()
    opts['padtype'] = opts.get('padtype', 'symmetric')
    opts['rpadded'] = opts.get('rpadded', 0)

    n = len(x)
    x, N, n1, n2 = padsignal(x, opts['padtype'])

    xMean = np.mean(x)
    x -= xMean

    # choosing more than this means the wavelet window becomes too short
    noct = np.log2(N) - 1
    assert(noct > 0 and noct % 1 == 0)
    assert(nv > 0   and nv   % 1 == 0)
    assert(dt > 0)
    assert(not np.any(np.isnan(x)))

    na = int(noct * nv)
    Wx_scales = np.power(2 ** (1 / nv), np.arange(1, na + 1))
    Wx_scales *= dt

    if not opts['rpadded']:
        x = x[n1:n1 + n]
    return x, Wx_scales

########### signals #################################################
t = np.linspace(0, 10, 2048)
s1 = (1 + .2*np.cos(t)) * np.cos(2*np.pi*(2*t   + .3*np.cos(t)))
s2 = (1 + .3*np.cos(t)) * np.cos(2*np.pi*(2.4*t + .3*np.sin(t) + .5*t**1.2)
                                 ) * np.exp(-t/15)
s3 = np.cos(2*np.pi*(5.3*t + 0.2*t**1.3))
N = np.random.randn(len(t)) * np.sqrt(2.4)
s  = s1 + s2 + s3
sN = s + N
viz_signal(t, s, sN, s1, s2, s3)

########### ssqueezepy ##############################################
OPTS = {'type': 'morlet', 'mu': 1}
Wx_s,  *_ = cwt_fwd(s,  'morlet', opts=OPTS)
Wx_sN, *_ = cwt_fwd(sN, 'morlet', opts=OPTS)
viz_compare(Wx_s, Wx_sN, cmap='bwr', norm_abs=(-1.3, 1.3),
            suptitle="SSQUEEZEPY [Processed Signal]")

########### pywt ####################################################
sx,  Wx_scales_sx  = _pre_pywt_cwt(s,  opts=OPTS)
sxN, Wx_scales_sxN = _pre_pywt_cwt(sN, opts=OPTS)

coef_s,  _ = pywt.cwt(s,  Wx_scales_sx,  'morl', method='fft')
coef_sN, _ = pywt.cwt(sN, Wx_scales_sxN, 'morl', method='fft')
viz_compare(coef_s, coef_sN, cmap='bwr', norm_abs=(-10, 10),
            suptitle="SSQUEEZEPY [Unprocessed Signal]")

coef_sx,  _ = pywt.cwt(sx,  Wx_scales_sx,  'morl', method='fft')
coef_sxN, _ = pywt.cwt(sxN, Wx_scales_sxN, 'morl', method='fft')
viz_compare(coef_sx, coef_sxN, cmap='bwr', norm_abs=(-10, 10),
            suptitle="SSQUEEZEPY [Processed Signal]")

########### both, real vs. imag #####################################
viz_re_im(Wx_s,   suptitle="SSQUEEZEPY")
viz_re_im(coef_s, suptitle="PYWT")

```

</details>

<hr>

![image](https://user-images.githubusercontent.com/16495490/79520154-0d384600-8067-11ea-9603-439973ddfc0a.png)

**Comment by Neurophile** [comment]
The lack of an imaginary component from pywt.cwt is due to the choice of wavelet. 'morl' is real valued, to get complex output use something like 'cmor1.5-1.0' where the 1.5 and 1.0 are the bandwidth and center frequency parameters as described in the pywavelets docs for cwt. I expect 1.0 center frequency is the correct choice but some digging is required to find what bandwidth param best matches the implementation in cwt_fwd.

**Comment by OverLordGoldDragon** [comment]
@grlee77 Thanks again for your early reviews. I've decided to proceed independent of PyWavelets, one reason being the apparent pace at which PR's are handled. I stand by `pywt` keeping its current CWT implementation as a valid and unique alternative to others'.
