### ISSUE TITLE
Request: add __reduce__ method for WaveletPacket object

### ISSUE THREAD

**Issue by tomasrojasc** [PyWavelets/pywt#545]
Hello, I am trying to pickle a wavelet object... Actually, many many that I wrapped in another object, but I am having this error

```python
TypeError: no default __reduce__ due to non-trivial __cinit__
```
This due to not having a `__reduce__` 
Here is a little code to be able to replicate my error:

```python
import pywt
import pickle

test = pywt.WaveletPacket([1, 2, 3, 4, 5, 6, 7, 8], 'haar')
with open('data', 'wb') as f:
    pickle.dump(test, f)
f.close()
```

**Comment by grlee77** [comment]
This sounds like a reasonable request. Please see PR #546 and see if that works for you. 

Unfortunately, trying it out will require building from source because a `__reduce__` method also had to be added to the `pywt.Wavelet` class which is defined in Cython.

**Comment by tomasrojasc** [comment]
Something is wrong, is giving me this error when importing 
```python
 File "<stdin>", line 1, in <module>
  File "/Users/mytorojas/Desktop/pywt-pickling/pywt/__init__.py", line 15, in <module>
    from ._extensions._pywt import *
ModuleNotFoundError: No module named 'pywt._extensions._pywt'
```

**Comment by grlee77** [comment]
This sounds like you have not compiled the Cython extensions. You can build them via `python setup.py build_ext` from within `/Users/mytorojas/Desktop/pywt-pickling/`.

Rather then running that setup command, I usually just use pip to install an in-place build. (i.e. navigate to  `/Users/mytorojas/Desktop/pywt-pickling/` and run

```
pip uninstall pywavelets -y
pip install -e . -v
```
To avoid messing up any existing environment you may want to something like `conda` or `virtualenv` to do this in a clean environment`

**Comment by tomasrojasc** [comment]
It works!

**Comment by tomasrojasc** [comment]
Yes, this solved the problem!
