### ISSUE TITLE
wavedec2() usage question

### ISSUE THREAD

**Issue by Fubuki901** [PyWavelets/pywt#555]
I want to use 2D multilevel biorthogonal wavelet transform. How should I choose a certain one in the family.('bior1.1','bior1.3', 'bior1.5','bior2.2',...)
Does it make much difference？
I am a beginner.

**Comment by rgommers** [comment]
This question has unfortunately gone unanswered for almost 3 years - I'm going to assume it's no longer relevant, and close the issue.
