### ISSUE TITLE
What is CWT based on?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [PyWavelets/pywt#556]
I'm porting synchrosqueezing to Python with interest of merging with PyWavelets; it uses its own CWT implementation, which differs from [pywt.cwt](https://github.com/PyWavelets/pywt/blob/master/pywt/_cwt.py#L37). I've been studying their [differences](https://github.com/OverLordGoldDragon/ssqueezepy/blob/viz/vs_pywt_cwt.md), but need the relevant formulas / literature for pywt.cwt to make sense of a need for two different implementations.

**Comment by grlee77** [comment]
I had found some info on where the current PyWavelets implementation comes from in https://github.com/PyWavelets/pywt/issues/531#issue-510962058, but don't have a better reference than that.

**Comment by OverLordGoldDragon** [comment]
[Resolved](https://github.com/PyWavelets/pywt/issues/531#issuecomment-702183035).
