### ISSUE TITLE
how to create integer to integer wavelet transform

### ISSUE THREAD

**Issue by koujiangheng** [PyWavelets/pywt#566]
how to create integer to integer wavelet transform using current pywavelet lib?

**Comment by grlee77** [comment]
Hi @koujiangheng, I see you already closed this, but will still answer briefly.

In short, you cannot perform an integer to integer wavelet transform with PyWavelets. I think these are typically implemented with a wavelet lifting transform which we do not currently have an implementation for (all DWT/SWT functions implemented use convolution with FIR filters having floating point coefficients).
