### ISSUE TITLE
new feature: iswt2

### ISSUE THREAD

**Issue by sciunto** [PyWavelets/pywt#57]
See https://github.com/nigma/pywt/issues/1

**Comment by rgommers** [comment]
That feature request makes sense. Would be good to add. We also still need to add the 1-D version.

**Comment by ThomasA** [comment]
It seems this feature is being worked on in #55 ?

**Comment by ThomasA** [comment]
I am starting to add some tests for `iswt` and `iswt2`. It seems that the existing tests for `swt` are in 'pywt/tests/test_multilevel.py' and there are no tests for `swt2`.
It seems pywt is not using `unittest` but relies on assertions to raise an error whenever something is not right - is this correct? So should I continue by adding tests for `iswt`, `iswt2`, and probably `swt2` to 'pywt/tests/test_multilevel.py' using the same assertion-style tests?

**Comment by ThomasA** [comment]
In #81 we have discussed moving `swt2` to 'multilevel.py'. Should I go ahead and place `iswt` and `iswt2` in 'multilevel.py' right away?

**Comment by sciunto** [comment]
I would vote to follow the scipy guidelines for the tests suite. I'll make the job easier for a future integration. @rgommers can probably confirm this.

**Comment by rgommers** [comment]
Putting them in ``multilevel.py`` now sounds fine to me.

**Comment by rgommers** [comment]
Regarding the tests, they're based on ``nose`` and ``numpy.testing`` which is pretty much the standard for the scientific Python stack. ``nose`` is definitely much more flexible/powerful than plain ``unittest`` - the only other serious contender is ``py.test``.

The testing guidelines are at https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt

So +1 for putting test cases in ``test_multilevel.py`` in the same style.

**Comment by rgommers** [comment]
No tests for ``swt2``: the test coverage is still lacking in places unfortunately. In 0.2.2 there were only doctests and now we're at 61% coverage, so it's going up nicely but more is needed.

**Comment by ThomasA** [comment]
I'll be happy to write tests for swt2 as well after I add some for iswt2 and iswt.

**Comment by rgommers** [comment]
That would be great!

**Comment by aaren** [comment]
Just leaving this here for reference as I've cut it from my #38 todo list. May or may not actually be useful.

- [ ] There are also iswt ([1][iswta], [2][iswtb], [3][iswtc]) and [iswt2] implementations posted on the
  PyWavelets mailing list.
    - [x] copy basic code from mailing list
    - [x] make basic implementation with simple test
    - [ ] do `swt` outputs need to be consistent with `dwt`?
    - [ ] decide if license ok
    - [ ] cythonize iswt code?
    - [ ] add istw2 to `pywt/_multidim.py`


[iswta]: https://groups.google.com/d/msg/pywavelets/bNFdhb6D5r0/9LnLdpW-PCsJ
[iswtb]: https://groups.google.com/d/msg/pywavelets/K_VKC29iIkY/_ZlowX9SYnIJ
[iswtc]: https://groups.google.com/d/msg/pywavelets/tLh9ObKJaoc/hksGDLHwGpMJ

[iswt2]: https://groups.google.com/d/msg/pywavelets/xk3UeFz9ZK0/mylNG7qUyKsJ

**Comment by ThomasA** [comment]
@aaren thanks for that. You mention license. Where do you see licensing info for the code on the mailing list? I don't think I came across it.
I am planning to use the `iswt` proposed on the mailing list, but the proposed `iswt2` does not work properly, so I have implemented it from scratch, basically doing what `iswt` does but with `idwt2`.
I should add that this is my approach because I need something working NOW. In the longer term, it would probably be a good idea to re-implement them (and possibly `swt2`) using a similar Cython approach to that of `swt`.

**Comment by aaren** [comment]
Licensing: I couldn't find anything either.

iswt: Yes, I think get something working that is tested and then optimise later.

**Comment by ThomasA** [comment]
Regarding licensing, maybe it is OK to just consider it approved for 
inclusion in pywt by the original author as it was posted as a 
suggestion on the pywt mailing list?

**Comment by aaren** [comment]
That's what we thought. Could ask on the [list](https://groups.google.com/forum/#!msg/pywavelets/bNFdhb6D5r0/vAcprEgxzycJ) to be safe.

**Comment by ThomasA** [comment]
Consider it done...

**Comment by mgmarino** [comment]
@ThomasA, @aaren: @ThomasA just contacted me on the mailing list. Of course it's fine to use, thanks for pulling in the code.

**Comment by ThomasA** [comment]
Great, thanks @mgmarino

**Comment by aaren** [comment]
@mgmarino that's great - thanks a lot :)

**Comment by kwohlfahrt** [comment]
Sorry, I'm a bit late to the discussion. I have a branch for a C convolution that would do the same as `up/downsampling_convolution` does for dwt, but it's based on top of #59. Hopefully I'll have #59 ready for merge this weekend now that we have Windows CI testing, and I'll open a PR for the swt part next week so you can have a look. Implementing swt on top of that in a similar manner as dwt should be possible.

**Comment by kwohlfahrt** [comment]
This is closed by #93
