### ISSUE TITLE
Wheels are missing for Python 3.9.

### ISSUE THREAD

**Issue by orlp** [PyWavelets/pywt#576]
Title pretty much says it all, there are no wheels available for Python 3.9 on pypi.

**Comment by grlee77** [comment]
Thanks @orip. I will try to get out a new release with Python 3.9 support in the near future.

**Comment by grlee77** [comment]
I uploaded Python 3.9 wheels for the 1.1.1 release to PyPI

**Comment by orlp** [comment]
Thanks for your quick solution.
