### ISSUE TITLE
 UserWarning: Level value of 1 is too high

### ISSUE THREAD

**Issue by kunyaoli** [PyWavelets/pywt#581]
UserWarning: Level value of 1 is too high: all coefficients will experience boundary effects.
  "boundary effects.").format(level))

I changed the level to 1, It's still have UserWarning, what should I do ?

**Comment by grlee77** [comment]
This message is indicating that the data size is shorter than the wavelet filter along at least one axis. To be more specific, you will have to provide more detail on what you are doing:

Which function are you calling?
What is the shape of the input? 
What wavelet are you using?

A common case where even 1 level would raise this error is if you are accidentally transforming along the "channels" axis of a color image (e.g. a dimension of size 3, but most wavelet filters are longer than 3 samples).

**Comment by kunyaoli** [comment]
> 
> 
> This message is indicating that the data size is shorter than the wavelet filter along at least one axis. To be more specific, you will have to provide more detail on what you are doing:
> 
> Which function are you calling?
> What is the shape of the input?
> What wavelet are you using?
> 
> A common case where even 1 level would raise this error is if you are accidentally transforming along the "channels" axis of a color image (e.g. a dimension of size 3, but most wavelet filters are longer than 3 samples).

thank you for your help , yes, maybe my data is shoter  than the wavelet filter.

`pywt.wavedec(data=data, wavelet=db4, level=1)`

my data is :[121.2, 136.2, 151.2, 166.2, 181.2, 196.2, 211.2, 226.2, 241.2, 256.2, 271.2, 286.2, 286.2] for input

I used visu_shrink mehod to chose the threshold value

I think the problem is the wavelet ， when I use db1， is have no error.

**Comment by kunyaoli** [comment]
> 
> 
> This message is indicating that the data size is shorter than the wavelet filter along at least one axis. To be more specific, you will have to provide more detail on what you are doing:
> 
> Which function are you calling?
> What is the shape of the input?
> What wavelet are you using?
> 
> A common case where even 1 level would raise this error is if you are accidentally transforming along the "channels" axis of a color image (e.g. a dimension of size 3, but most wavelet filters are longer than 3 samples).

it‘s still have the same problem  when  rerun the `pywt.wavedec(data=data, wavelet=db1, level=1)` .

**Comment by kunyaoli** [comment]
thx，it‘s the wavelet and layer  have wrong values to put in。

**Comment by margueritetalamon** [comment]
Hello, how have you done finally please ? 
I have the same warning when applying wavelet on images
