### ISSUE TITLE
Failure at pip install 

### ISSUE THREAD

**Issue by pundemonium** [PyWavelets/pywt#585]
Windows 10, installing to python 3.4.4, numpy and Cython installed, using compiler from  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\cl.exe

Also tried installing to python 3.8.0, got same log.
Error lines in the log:
 building 'c_wt' library
    creating build\temp.win-amd64-3.4
    creating build\temp.win-amd64-3.4\pywt
    creating build\temp.win-amd64-3.4\pywt\_extensions
    creating build\temp.win-amd64-3.4\pywt\_extensions\c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DPY_EXTENSION -Ipywt\_extensions\c -Ic:\users\punis\appdata\local\programs\python\python34\include /Tcpywt\_extensions\c/common.c /Fobuild\temp.win-amd64-3.4\pywt\_extensions\c/common.obj
    common.c
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(79): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(110): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(141): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(153): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(163): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(174): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(184): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(194): error C2059: 语法错误:“[”
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\codeanalysis\sourceannotations.h(206): error C2059: 语法错误:“[”
    pywt\_extensions\c/common.c(29): warning C4244: “return”: 从“unsigned long”转换到“unsigned char”，可能丢失数据
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\punis\appdata\local\programs\python\python34\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\punis\\AppData\\Local\\Temp\\pip-install-j5jzla1k\\pywavelets\\setup.py'"'"'; __file__='"'"'C:\\Users\\punis\\AppData\\Local\\Temp\\pip-install-j5jzla1k\\pywavelets\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\punis\AppData\Local\Temp\pip-record-n7g44xqy\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

Full log attached below:
[log.txt](https://github.com/PyWavelets/pywt/files/6075336/log.txt)

**Comment by rgommers** [comment]
Python 3.4 hasn't been supported for a long time. Please update your Python version, or install an old PyWavelets version that does support it (use `pip install pywavelets=0.5.2  # last version to support py34`)
