### ISSUE TITLE
Question: Do you have interactive demos, like the maltet wavelet toolbox

### ISSUE THREAD

**Issue by theRealSuperMario** [PyWavelets/pywt#599]
Hi

1. Thanks for putting in the hard work and building the pywt package. It really is awesome.
2. I was wondering if (and where) you might have some interactive tools to play around with when looking for the right wavelet  filter, filter level, etc... Maybe it is somewhere around here already, but I did not find it yet.

Let me know. Cheers guys

**Comment by rgommers** [comment]
Hi @theRealSuperMario, http://wavelets.pybytes.com has this. That site was built by the original PyWavelets author.

Question is answered, so I'll close this issue.
