### ISSUE TITLE
Why are the return parameters of the two links different

### ISSUE THREAD

**Issue by qazzombie** [PyWavelets/pywt#619]
Why the return parameters of    https://github.com/PyWavelets/pywt/blob/4c6e34af973badcdccba42ddbf55d850ea014d58/pywt/_multidim.py#L156-L160   and   https://pywavelets.readthedocs.io/en/v1.1.1/ are different

**Comment by rgommers** [comment]
The second link just points at the front page of the docs, so the question is unclear. There doesn't seem to be a bug in the docs, so I'll close this. @qazzombie please feel free to explain in more detail and I'll have another look.
