### ISSUE TITLE
Change Contrast Of Image

### ISSUE THREAD

**Issue by AzadKshitij** [PyWavelets/pywt#632]
How can I change contrast of image using this library?
Any Example?

**Comment by grlee77** [comment]
We do not have any functions specifically for contrast-manipulation. If you have a specific wavelet-based method from the literature in mind, we can perhaps advise on how to perform the technique using the wavelet transforms implemented here.

Alternatively, there are a number of non-wavelet methods for contrast modification in scikit-image, particularly within `skimage.exposure` ([gallery examples](https://scikit-image.org/docs/stable/auto_examples/#manipulating-exposure-and-color-channels))

**Comment by grlee77** [comment]
I am closing this as not a bug or issue with the library, but feel free to continue the discussion here
