### ISSUE TITLE
3 Level decomposition using Haar wavelet

### ISSUE THREAD

**Issue by Its-NK** [PyWavelets/pywt#634]
**Can anyone help me write python script to decompose an image upto 3 Low levels using haar wavelet ?**? to gain low level detail for upto 3 levels. As i am new to this field and i am facing lots of problems here.

**Comment by rgommers** [comment]
I'm sorry, we (the two active maintainers) don't have bandwidth to help with custom usage questions beyond improving the docs. I hope you figured it out after you asked this.
