### ISSUE TITLE
Integer wavelet transform

### ISSUE THREAD

**Issue by christofer-f** [PyWavelets/pywt#638]
Hi,
Is the integer wavelet transform implemented?

I am looking for the transform that s used for lossless compression in jpeg2000. CDF 5/3. 

If possible it would be great with a short example.

**Comment by christofer-f** [comment]
this issue can be closed... I created the code myself...

https://github.com/christofer-f/IntegerWaveletTransform

**Comment by rgommers** [comment]
Thanks @christofer-f
