### ISSUE TITLE
arbitrary waveform

### ISSUE THREAD

**Issue by wyokota3** [PyWavelets/pywt#646]
Hi!!

In pywavlet, dB, MexicanHat, etc. are provided by default, but if I want to use an arbitrary waveform (for example, the waveform of a particular sound I want to extract) as the mother wavelet, how can I implement this?

**Comment by rgommers** [comment]
There's a section in the docs on this: https://pywavelets.readthedocs.io/en/latest/ref/wavelets.html#custom-wavelets.
