### ISSUE TITLE
numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by QGN123** [PyWavelets/pywt#658]
![8fc587e5eea8330044be5e5f4f9f1a3a](https://user-images.githubusercontent.com/38217558/190611714-82f84ee7-90f0-4013-94ff-a66cbaf4930c.png)

python3.7.13
numpy1.19.5
centos6

**Comment by QGN123** [comment]
pywt 1.4.0

**Comment by rgommers** [comment]
@QGN123 can you please add how you installed Python, NumPy and PyWavelets?

**Comment by rgommers** [comment]
I checked, there were no wheels for 3.7, so this was a build from source. The `pyproject.toml` requirements say:
```
"numpy==1.17.3; python_version=='3.7' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64' and platform_python_implementation != 'PyPy'",
```
So a `pip install pywavelets` should have built against numpy `1.17.3`. At runtime, `1.19.5` must work then. The error message indicates that the wheel was somehow built against a newer numpy version than `1.19.5`. Maybe you used `python setup.py install` in an environment with a newer `numpy` already installed?

**Comment by Yanyu000** [comment]
I have the same issue. My python --version is Python 3.10.1 and numpy version is 1.24.2. I have tried to upgrade my numpy but it does not work. I need pywt to do my school project. I'd be grateful if this problem can be solved.

**Comment by rgommers** [comment]
This error is guaranteed to go away if you install the latest numpy. There's nothing else that can be done here - a `pip install numpy pywavelets` will always work.
