### ISSUE TITLE
Where can i find relevant code implementation of the function named "double_downcoef_axis"

### ISSUE THREAD

**Issue by weweus** [PyWavelets/pywt#659]

**Comment by steph2016** [comment]
hello,
thanks for asking again : I can't find this information.....

**Comment by mattip** [comment]
It is templated via TYPE, where TYPE can be a number of float/complex float type s https://github.com/PyWavelets/pywt/blob/4591748823f2259844b6b3de0ddf60d1a85a6fa7/pywt/_extensions/c/wt.template.c#L27

**Comment by rgommers** [comment]
The question was answered, so I'll close this issue. Thanks all
