### ISSUE TITLE
need detailed and clear descriptions of algoritms

### ISSUE THREAD

**Issue by steph2016** [PyWavelets/pywt#660]
In the framework of a project where I need to run wavelet algorithms coded in fortran, I need a detailed and clear description of algorithms in pywavelets. It would be very convenient to also have testing results that where tried during this module building. Where can I find that ?

**Comment by rgommers** [comment]
See `pywt/tests` for our test suite. It also contains data with reference results from testing against Matlab.

There are references in the docs, that's as much as there is regarding algorithms.

There's nothing to do here, so I'll close this issue.
