### ISSUE TITLE
Any C/C++ API/interface?

### ISSUE THREAD

**Issue by Meso272** [PyWavelets/pywt#662]
Hi,
I'm interested in embedding several of your implemented wavelet transforms into a C++ code project, so I'd like to know if there's any C/C++ API/interface available for using the transforms provided in this package? Thanks.

**Comment by rgommers** [comment]
@Meso272 there isn't a C/C++ API unfortunately. Even if that could be exposed, the implementations are in Cython which means you'd pull in CPython - probably not what you want for a C or C++ project.

**Comment by Meso272** [comment]
> 
Thanks!

**Comment by cl886699** [comment]
Hi, have find any useseful c/c++ api
