### ISSUE TITLE
[question] create CWT filter bank

### ISSUE THREAD

**Issue by JXuann** [PyWavelets/pywt#672]
Hi,

I would like to know if there is an equivalent function of matlab's [CWT filter bank](https://www.mathworks.com/help/wavelet/ref/cwtfilterbank.wavelets.html) in pywt?

Many thanks!

**Comment by rgommers** [comment]
I'm sorry, we (the maintainers) have extremely limited bandwidth to work on this package, and can't answer questions like these.
