### ISSUE TITLE
Enhanced documentation for CWT

### ISSUE THREAD

**Issue by drs251** [PyWavelets/pywt#676]
IMO, the documentation for `pywt.cwt` could use a more detailed example, e.g. generating a chirp signal and creating a scaleogram using the complex Morlet wavelet, possibly with several different bandwidths and center frequencies. Ideally, this should also give some hints how to choose scales and wavelets and how to visualize the result. Also, a link to Torrence & Compo's paper (https://paos.colorado.edu/research/wavelets/bams_79_01_0061.pdf) would be helpful for users.

I was having a hard time getting started with the CWT, also because of the lack of good documentation elsewhere. If you think this is a good idea, I'll get started on a PR.

**Comment by rgommers** [comment]
Thank you @drs251, a PR like that would be very welcome.
