### ISSUE TITLE
Upload dev builds for all supported platforms to anaconda.org

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#712]
After gh-710 we are uploading `wasm32` wheels to https://anaconda.org/scientific-python-nightly-wheels/PyWavelets/. It'd be useful to upload wheels we're building for releases to that location as well. That way, projects like `scikit-image` that depend on PyWavelets can test with nightlies.

The relevant job is [wheel_tests_and_release.yml](https://github.com/PyWavelets/pywt/blob/master/.github/workflows/wheel_tests_and_release.yml)

**Comment by rgommers** [comment]
This isn't urgent, but would be nice to do sometime in the next couple of weeks. Would you be able to do this @agriyakhetarpal?

**Comment by agriyakhetarpal** [comment]
Sure! Please feel free to assign me to this, I'll keep this on my radar. I assume the same rules apply for all other platforms as well? i.e., on 3rd and the 17th of the month, every push to `master`, etc.?

**Comment by rgommers** [comment]
Great, thanks. Yes, same rules/frequency would be good.

**Comment by agriyakhetarpal** [comment]
Cross-posting from https://github.com/PyWavelets/pywt/pull/714#issuecomment-1992170197. I have marked the PR to not close this issue, we can target MUSL wheels and native macOS arm64 wheels and that subsequent PR can close this issue.

**Comment by rgommers** [comment]
Implemented in gh-712 and gh-714, so closing. Thanks @agriyakhetarpal
