### ISSUE TITLE
How is CWT cmor wavelet defined?

### ISSUE THREAD

**Issue by cyschneck** [PyWavelets/pywt#735]
I am working on replicating behavior from Torrence and Compo in PyWavelets using the Complex Morlet function. The Morlet function in the Torrence and Compo is not a Morlet function, but a Complex Morlet function, so it should be similar to the `cmor` function in PyWavelets. 

Previously, a `cmor1.5-1.0` [was recommended](https://github.com/PyWavelets/pywt/issues/522#issuecomment-539227912). While this is close, the wavelets do not match.
![Untitled](https://github.com/PyWavelets/pywt/assets/22159116/3f5caac1-3564-441f-a479-da82b89f58cf)

I think essentially the issue that I've encountered is that the definition of the Complex Morlet function in [Torrence and Compo (Table 1)](https://psl.noaa.gov/people/gilbert.p.compo/Torrence_compo1998.pdf) is:
![image](https://github.com/PyWavelets/pywt/assets/22159116/375053ed-d15f-481b-9a70-a5eaf6a9cc36)

Whereas the [PyWavelets Complex Morlet Wavelet is defined as](https://pywavelets.readthedocs.io/en/latest/ref/cwt.html#complex-morlet-wavelets):
![image](https://github.com/PyWavelets/pywt/assets/22159116/f42a0cc8-5db3-414e-bad6-a9b0188aa073)

While this seems to match the equation for a [Complex Morlet Wavelet that is in Matlab](https://www.mathworks.com/help/wavelet/ref/cmorwavf.html), the equation does not match the Torrence/Compo paper that is referenced at the top of the CWT page.

There does not doesn't appear to be any definitions of bandwidth and center frequency that can be used in `cmor` that will make the behaviors match since Torrence and Compo is using $\pi$^ (-0.25) and PyWavelets is using $\pi$ ^ (-0.5)

The [wiki definition](https://en.wikipedia.org/wiki/Morlet_wavelet) and [SciPy's Morlet function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.morlet.html) (before it was deprecated) also appear to match the equation described in Torrence/Compo. Where does PyWavelet's definition of a Complex Morlet come from?

**Comment by rgommers** [comment]
Great question @cyschneck. Unfortunately I really don't know the answer. I think it's been like this since it was first written (before 2010).

**Comment by cyschneck** [comment]
Thanks, I'll have to keep digging

For future reference, based on some research I believe this originated from the same equation used for the [Complex Morlet in Matlab](https://www.mathworks.com/help/wavelet/ref/cmorwavf.html) from _Computational Signal Processing with Wavelets_
```
Teolis, Anthony. Computational Signal Processing with Wavelets. Boston, MA: Birkhäuser Boston, 1998. https://doi.org/10.1007/978-1-4612-4142-3. 
```
On page 65-66, the Morlet wavelet is referred to as:
![image](https://github.com/PyWavelets/pywt/assets/22159116/91257e08-d48d-4c0d-a699-020e445a17af)
![image](https://github.com/PyWavelets/pywt/assets/22159116/78bdd006-94f8-485b-9083-5e3af8dc1158)
![image](https://github.com/PyWavelets/pywt/assets/22159116/9ac3602d-fd0d-4c13-b062-bd82964aa4a7)
Specifically, the (mother) Morlet wavelet is defined as:
![image](https://github.com/PyWavelets/pywt/assets/22159116/80a43f3f-238f-4e54-b7d2-a3e8be89233f)
Which seems to match PyWavelets:
![321322221-f42a0cc8-5db3-414e-bad6-a9b0188aa073](https://github.com/PyWavelets/pywt/assets/22159116/3fd973f2-34d6-4d6b-add9-487c3b4365ac)
I'll need to keep looking to see why it is defined differently in this one reference location compared to the more common definition I see elsewhere since both the Teolis book and the Torrence/Compo paper came out in the same year, but thanks!

**Comment by cyschneck** [comment]
While the amplitude is different, the closest match I've found is a bandwidth of sqrt(pi) and a center frequency of 6/2*pi (so it is close to the default Morlet of 6). The amplitude difference is the result of some constant that is missing that Torrence/Compo is using. I'll see if I can find where they derive their equation with the $\pi$^(-1/4) from
![Untitled](https://github.com/PyWavelets/pywt/assets/22159116/7c94bf0d-63cd-4e1d-8266-732f3ddff946)

**Comment by cyschneck** [comment]
So, for future reference, using  `B=sqrt(pi)` and `C=6/2pi` produces the graph above, with the same intersects along 0.0, but a smaller amplitude. 

To generate a matching wavelet, B needs to somehow be both `2` and `sqrt(pi`) to match the Torrence and Compo formula:

![image](https://github.com/PyWavelets/pywt/assets/22159116/375053ed-d15f-481b-9a70-a5eaf6a9cc36)

To match, setting `B=2` and multiplying the entire wavelet by a constant value `sqrt(2)*pi^(1/4)`

![Untitled](https://github.com/PyWavelets/pywt/assets/22159116/2db41ebd-361a-4507-8782-5dda1ba7d4ed)

**Comment by rgommers** [comment]
Thank you for all the details @cyschneck! I am sure this will help the next person who looks into this definition.

**Comment by spluque** [comment]
Great work @cyschneck. It seems that the two formulations for the Morlet function are in regular use.

I have a follow-up question, as I'm just beginning to learn about wavelets: how should the coefficients and frequencies returned by Pywavelets' `cwt` function be transformed to match Torrence & Compo (1998)? I'm not sure if the wavelet object itself can be modified accordingly, instead of modifying the output. Any insights appreciated.

**Comment by cyschneck** [comment]
Yeah @spluque, the best I could find was to set `B=2` and `C=6/2pi` (`cmor2-0.9549...`) and multiplying the entire wavelet by a constant value `sqrt(2)*pi^(1/4)` ([see above](https://github.com/PyWavelets/pywt/issues/735#issuecomment-2075937473)). That set the Complex Morlet outputs to match the intersection with zero and the amplitude and should give you the coeffs are you are looking for. Without the constant it won't have the same amplitude. As it stands `cwt` uses a fundamentally different equation and I didn't see a way to modify the wavelet object to make it match otherwise.

I used a different Complex Morlet in this [Pythia example](https://projectpythia.org/wavelet-cookbook/notebooks/example-workflows/nino3.html) (`cmor1.5-1`) for simplicity (might change it in the future), but this workflow might have more details you could find useful if you are looking into Torrence and Compo

**Comment by spluque** [comment]
The relationship between the two formulations is clear once the bandwidth and center frequency are mapped between them as you've shown, which reveals why the $\sqrt{2} \pi ^ {1/4}$ factor is required to match the two wavelets. However, the latter factor needs to be accounted for in the transform so that the output coefficients and frequencies match. It should be possible to do that.

Thanks for the Project Pythia reference.
