### ISSUE TITLE
Moving to a Github org

### ISSUE THREAD

**Issue by rgommers** [PyWavelets/pywt#82]
Hi all, I've just created https://github.com/PyWavelets. I suggest that we move my repo (including all issues and PRs) to that org now, and then advertise that in the v0.3.0 release notes. This works better than to keep developing in my personal fork.

It should work without any delay: https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by rgommers** [comment]
I've added @nigma @aaren @grlee77 and @kwohlfahrt as owners on the organization - these are all the people who have put significant time into PyWavelets until this point.

**Comment by rgommers** [comment]
I have also added a "core contributors" team there, to which we can add new developers who want to join and that we want to give commit rights. An org shouldn't have too many owners, since that level is not about commit rights but about control over the Github org itself (there's a button to delete the org or a repo - which is not reversible...).

**Comment by rgommers** [comment]
The only thing to do for everyone after the repo is moved is to update their remotes. Typically this repo would be called ``upstream`` (and your own fork ``origin``). The fastest way to do this is ``$ vim .git/config``, then change ``rgommers`` in the below to ``PyWavelets``:

    [remote "upstream"]
            url = git@github.com:rgommers/pywt.git
            fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*

Note that the ``fetch`` line may not be there for you - it's very handy to add it. Then you'll get all submitted PRs when fetching from upstream.

**Comment by grlee77** [comment]
+1
Thanks @rgommers.  Seeing how everything comes together for the release has been a good learning experience.

**Comment by rgommers** [comment]
@grlee77 that's always good to hear!

**Comment by grlee77** [comment]
just a quick note that each of us have to accept the invitation from Ralf to join the PyWavelets organization.  I just did so (and updated my github profile to use two-factor authentication for security).

@rgommers:  Do you want to specify a specific time for the move?  It looks like after the move and the merging of #78, #79 and maybe #76 we should be ready for the 0.3.0 release.

**Comment by rgommers** [comment]
Tonight maybe? I'd like to do the v0.3.0 release asap. Then we can move on to merging all the other open PRs and v0.4.0. FYI: I'll be completely offline from Aug 24th to mid-October. So I'm hoping to do v0.4.0 before Aug 24. Or you guys could do that one without me if we just miss that date.

**Comment by grlee77** [comment]
sounds good

**Comment by grlee77** [comment]
Aug 24 sounds like a good time for v0.4.0.  I will be out the first two weeks of September, but will otherwise be around.

**Comment by rgommers** [comment]
Allright, pulled the trigger here. Nothing got lost in transit it looks like.

**Comment by rgommers** [comment]
Even TravisCI magically gets updated once you move the repo!

**Comment by rgommers** [comment]
All the redirects from rgommers/pywt to PyWavelets/pywt work well, so I'll wait a bit in re-forking to my personal account (because that should break those redirects). Will do that after the release announcement has been out for some days.
