### ISSUE TITLE
The documentation on readthedoc is not up to date

### ISSUE THREAD

**Issue by sciunto** [PyWavelets/pywt#89]
Compare for instance
https://pywavelets.readthedocs.org/en/latest/#contributing
and the source.

**Comment by sciunto** [comment]
I just figured out that the doc is linked to the original project. Should we fork the doc? Otherwise, it's confusing.

**Comment by rgommers** [comment]
The documentation link on PyPi is http://pythonhosted.org/PyWavelets/, which is already up-to-date. I have the rights to the ReadTheDocs repo and pointed it to this repo, so now I'll just have to convince it to rebuild.

**Comment by rgommers** [comment]
It's rebuilding now.

**Comment by rgommers** [comment]
http://pywavelets.readthedocs.org/en/latest/ is up-to-date now, v0.3.0 is rebuilding and will be updated in a few minutes. So closing. Thanks for noticing this @sciunto

**Comment by aaren** [comment]
How did you trigger the rebuild?

**Comment by aaren** [comment]
I've added readthedocs to the repo [services](https://github.com/PyWavelets/pywt/settings/hooks) so that it rebuilds on commit.

**Comment by rgommers** [comment]
It apparently auto-rebuilds if something changes. But what was missing was the right build dependencies - pointing ReadTheDocs to ``util/appveyor/requirements.txt`` did the job.

**Comment by rgommers** [comment]
Instant rebuilds - nice.
