### ISSUE TITLE
PyWavelets vs. nigma Github repo

### ISSUE THREAD

**Issue by cdeil** [PyWavelets/pywt#90]
I noticed that the "fork on Github" button at http://pywavelets.readthedocs.org/ still points to https://github.com/nigma/pywt

So I wanted to change it to point to https://github.com/PyWavelets/pywt and use Github search to find the location in the code / docs where this is set.

But code search in forked repos doesn't work: https://help.github.com/articles/searching-code/#search-by-the-number-of-forks-the-parent-repository-has

I'm not sure ... maybe this could be resolved by deleting https://github.com/nigma/pywt and then forking it from https://github.com/PyWavelets/pywt ?
https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/

cc @nigma @rgommers

**Comment by jenshnielsen** [comment]
I have solved a number of similar issues by contacting github support, explain the situation and ask them to detach the repository from the original one.

**Comment by aaren** [comment]
@cdeil good spot, thank you. Agreed, it's annoying that you can't search in forks!

**Comment by cdeil** [comment]
This issue was closed, but is only partly adressed.
I think what @jenshnielsen proposed, that you ask Github to detach this fork (or revert which is the fork) would be a good solution.

**Comment by aaren** [comment]
@cdeil sorry, I was overeager. I think I understand now - the problem is that the code in this repository is unsearchable in the browser (the links were a separate problem), right?

This is caused by this repo being a fork of nigma/pywt.

**Comment by cdeil** [comment]
@aaren – Yes.

**Comment by aaren** [comment]
I've contacted github support.

**Comment by aaren** [comment]
Ok, Pywavelets/pywt added to index and code is now searchable.

**Comment by aaren** [comment]
Something else we could do: make PyWavelets the root repository so that future forks show up as forks of PyWavelets/pywt rather than nigma/pywt.

**Comment by rgommers** [comment]
Nice quick resolution of this issue.

> Something else we could do: make PyWavelets the root repository so that future forks show up as forks of PyWavelets/pywt rather than nigma/pywt.

I think forks that are made from PyWavelets/pywt will anyway show up as forked from there, see https://github.com/PyWavelets/pywt/network and https://github.com/aaren/pywt for example. So I don't think it's a major issue that this repo says it's forked from @nigma's repo - because that is the actual history of the project.

**Comment by cdeil** [comment]
It's still confusing to have the active repo shown as a fork.
Also https://github.com/nigma/pywt currently has 133 stars, but https://github.com/PyWavelets/pywt only 23, so I think Google (and Github?) search will point people there.

One other thing you could do is close the issue tracker on the old repo: https://github.com/nigma/pywt/issues
And close the PRs on the old repo (https://github.com/nigma/pywt/pulls), leaving a comment pointing to the new repo.

**Comment by rgommers** [comment]
Good points. I can update https://github.com/nigma/pywt, so its README points here and I can close the issue tracker (assuming Github lets me do that without deleting the issue history).

**Comment by rgommers** [comment]
@nigma had already updated the README on https://github.com/nigma/pywt, it now points prominently to this repo

**Comment by rgommers** [comment]
All PRs on https://github.com/nigma/pywt are closed, and I've only left a single issue open (https://github.com/nigma/pywt/issues/13) which is titled "Continuing PyWavelets development on PyPi" and still needs resolving.
