### ISSUE TITLE
Appveyor builds

### ISSUE THREAD

**Issue by kwohlfahrt** [PyWavelets/pywt#94]
Appveyor builds are triggering, but status is not shown on PRs. The appveyor URL still has `rgommers` in it, so I think this might have been missed in the move.

**Comment by kwohlfahrt** [comment]
@rgommers Thread [here](http://help.appveyor.com/discussions/problems/142-unable-to-create-a-project-from-github-org-account) suggests you might have to re-authorize Appveyor for org repos to work correctly. Sorry if you've done that already.

**Comment by rgommers** [comment]
Thanks @kwohlfahrt, I've tried this now. The problem is that by now I find it hard to reproduce what I have done before on Appveyor, because there are settings in three places: on ci.appveyor.com, in the webhooks of this repo, and in ``appveyor.yml``.

**Comment by rgommers** [comment]
Let's see if it's reporting the status for the next PR. It's smart enough to not rebuild on close/reopen of a PR apparently.

**Comment by kwohlfahrt** [comment]
No luck on #112

**Comment by rgommers** [comment]
I'm playing with this some more now.

**Comment by rgommers** [comment]
It still refuses to report anything, no idea why. I set up everything the same as for rgommers/pywt, on which it is working.

It is building though: https://ci.appveyor.com/project/PyWavelets/pywt/build/1.0.2

**Comment by aaren** [comment]
Tried changing content-type to `application/x-www-form-urlencoded` in the webhook settings, but this didn't make any difference when I modified #116. Tried both close/open and new commit - both triggered builds, but neither show up in the pr status.

**Comment by aaren** [comment]
The Appveyor response to the POST is unchanged - remains as 204.

**Comment by aaren** [comment]
Also tried the above in the organisation level webhooks, but no change.

It is confusing that there are Appveyor webhook settings on both the org and the repo.

**Comment by kwohlfahrt** [comment]
It looks like every test is run twice now. I think this might be because the webhook is set in both the [organization](https://github.com/organizations/PyWavelets/settings/hooks) and [repository](https://github.com/PyWavelets/pywt/settings/hooks).

**Comment by rgommers** [comment]
The repo webhook is the right one to keep I think, so removed the org one.

**Comment by grlee77** [comment]
This has now been fixed (see #133).
