### ISSUE TITLE
Simplify Matlab tests

### ISSUE THREAD

**Issue by ThomasA** [PyWavelets/pywt#95]
Decorate the `check_accuracy` in 'test_matlab_compatibility.py' as "slow" and simplify it to test way fewer data sizes to speed up testing and optionally disable Matlab tests unless full test suite is requested. See #92.

**Comment by rgommers** [comment]
Good idea to open a new issue to not lose track of this. We may want to keep the discussion on gh-92 though.

**Comment by grlee77** [comment]
addressed by #100 .

The new default is to run the tests using precomputed results at a reduced set of sizes.  The previous extended set of sizes is only tested if the PYWT_XSLOW environment variable is set.
