### ISSUE TITLE
BUG: erroneous detail coefficients returned by downcoef with level > 1

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#97]
As pointed out by @jairongfu in #72, it seems that there is still a problem for ``downcoef`` with detail coefficients and level > 1.  Unfortunately, the tests i added in #72 only tested the approximation case!

example reproducing the problem:
```python
import pywt
import numpy as np
from numpy.testing import assert_array_almost_equal
r = np.random.randn(16)
a2, d2, d1 = pywt.wavedec(r, 'haar', level=2)

assert_array_almost_equal(a2, pywt.downcoef('a', r, wavelet='haar', level=2))
assert_array_almost_equal(d2, pywt.downcoef('d', r, wavelet='haar', level=2))
```
The second ``assert_array_almost_equal`` call above fails, but the first passes.

**Comment by grlee77** [comment]
I found the bug and will submit a pull request shortly.  For the ``downcoef`` case, ``double_dec_a`` should be called up until the last level (when ``double_dec_d`` would be called).

**Comment by rgommers** [comment]
Fixed in gh-98.
